import {beltPulleyOverlap} from './belt-contact.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
import {governorEquilibrium} from '../mujoco-ball-governor/equilibrium.js';
import {beltGovernorGeometry,beltGovernorLinkage} from './geometry.js';

// Unregistered native study: one spindle actuator, passive flyballs, sleeve,
// cranked lever, connecting rod and guided belt fork. Ideal bearing constraints
// represent the nonrotating collar and fork sliding radially in its groove.
export function makeBeltGovernorPhysics(mujoco,{timestep=.0005,period=10,speedAmplitude=.15,spindleDrive=true,linkage=true,loadScale=1,ballContact=true,belt=true,beltFriction=.35,beltNormalForce=10,beltLoad=.1}={}){
 const g=beltGovernorGeometry(),initial=governorEquilibrium(g.initialSpread,g),lowerAngle=initial.lowerAngle;
 const linkagePotential=sleeve=>{const s=beltGovernorLinkage(sleeve,g);return g.gravity*((g.collarMass+g.followerMass)*sleeve+g.bellArmMass*(sleeve-g.grooveDrop+g.bellY)/2+g.bellArmMass*(s.outputY+g.bellY)/2+g.rodMass*(s.outputY+s.forkY)/2+g.forkMass*s.forkY);};
 const eps=1e-5,plus=governorEquilibrium(g.initialSpread+eps,g),minus=governorEquilibrium(g.initialSpread-eps,g);
 const extraSlope=linkage?loadScale*(linkagePotential(plus.sleeveY)-linkagePotential(minus.sleeveY))/(2*eps):0;
 const nominalSpeed=Math.sqrt(2*(initial.potentialSlope+extraSlope)/initial.inertiaSlope),k=2*Math.PI/period;
 const drive=t=>({angle:nominalSpeed*t+speedAmplitude*(1-Math.cos(k*t))/k,speed:nominalSpeed+speedAmplitude*Math.sin(k*t)});
 let arms='',constraints='';
 for(const sign of [-1,1]){
  const n=sign<0?'left':'right';
  arms+=`<body name="${n}" pos="${sign*g.pivotRadius} 0 0" euler="0 0 ${sign*g.initialSpread}"><joint name="${n}-spread" axis="0 0 ${sign}" damping=".08"/><geom type="capsule" fromto="0 0 0 0 -${g.ballArm} 0" size="${g.upperRadius}" mass="${g.upperMass}"/><geom name="${n}-ball" type="sphere" pos="0 -${g.ballArm} 0" size="${g.ballRadius}" mass="${g.ballMass}"/><body name="${n}-link" pos="0 -${g.elbowArm} 0" euler="0 0 ${sign*(lowerAngle-g.initialSpread)}"><joint name="${n}-link" axis="0 0 ${sign}" damping=".02"/><geom type="capsule" fromto="0 0 0 0 -${g.lowerLink} 0" size="${g.lowerRadius}" mass="${g.lowerMass}"/><geom name="${n}-link-stem" type="box" pos="0 -${g.lowerLink/2} .17" size=".054 ${g.lowerLink/2} .055" mass="0"/><site name="${n}-end" pos="0 -${g.lowerLink} 0"/></body></body>`;
  constraints+=`<connect site1="${n}-end" site2="${n}-sleeve"/>`;
 }
 const fy=g.sleeveY-g.grooveDrop-g.bellY,nominal=beltGovernorLinkage(g.sleeveY,g);
 const lever=linkage?`<body name="collar" pos="0 ${g.sleeveY-g.grooveDrop} 0"><joint name="collar" type="slide" axis="0 1 0"/><inertial pos="0 0 0" mass="${g.collarMass*loadScale}" diaginertia=".00001 .00001 .00001"/><body name="groove-follower"><joint name="radial-slide" type="slide" axis="1 0 0"/><inertial pos="0 0 0" mass="${g.followerMass*loadScale}" diaginertia=".000001 .000001 .000001"/><site name="groove"/></body></body><body name="bell" pos="${g.bellX} ${g.bellY} 0"><joint name="bell" axis="0 0 1" damping=".005"/><geom type="capsule" fromto="0 0 0 -${g.bellX} ${fy} 0" size=".035" mass="${g.bellArmMass*loadScale}"/><geom type="capsule" fromto="0 0 0 ${g.outputArm} 0 0" size=".035" mass="${g.bellArmMass*loadScale}"/><site name="bell-follower" pos="-${g.bellX} ${fy} 0"/><body name="rod" pos="${g.outputArm} 0 0"><joint name="rod" axis="0 0 1" damping=".005"/><geom type="capsule" fromto="0 0 0 0 -${g.rodLength} 0" size=".035" mass="${g.rodMass*loadScale}"/><site name="rod-end" pos="0 -${g.rodLength} 0"/></body></body><body name="fork" pos="${g.bellX+g.outputArm} ${nominal.forkY} 0"><joint name="fork" type="slide" axis="0 1 0" damping=".02"/><geom type="box" size=".10 .1 .1" mass="${g.forkMass*loadScale}"/><site name="fork-end"/></body>`:'';
 if(linkage)constraints+='<joint joint1="collar" joint2="sleeve" polycoef="0 1 0 0 0"/><connect site1="groove" site2="bell-follower"/><connect site1="rod-end" site2="fork-end"/>';
 const pairs=ballContact?'<contact>'+['left','right'].map(n=>`<pair geom1="${n}-ball" geom2="${n}-link-stem" solref=".002 1" solimp=".9999 .9999 .001" friction=".15 .15 .001 .0001 .0001"/>`).join('')+'</contact>':'';
 const beltBodies=belt&&linkage?`<body name="loose-pulley" pos="0 ${g.middlePulleyY} 0"><joint name="loose" axis="0 1 0" damping=".0002"/><inertial pos="0 0 0" mass=".05" diaginertia=".003 .005 .003"/></body><body name="belt-travel"><joint name="belt-travel" type="slide" axis="1 0 0" damping=".01" frictionloss="${beltLoad}"/><inertial pos="0 0 0" mass=".05" diaginertia=".001 .001 .001"/></body>`:'';
 const beltForces=()=>{
  if(!(belt&&linkage))return null;
  const overlap=beltPulleyOverlap(nominal.forkY+p.data.qpos[dofs.fork],g),v=p.data.qvel[dofs['belt-travel']],radius=g.pulleyRadius;
  const force=(width,speed)=>beltFriction*beltNormalForce*width/overlap.beltWidth*Math.tanh((radius*speed-v)/.05);
  return{overlap,fast:force(overlap.upper+overlap.lower,p.data.qvel[dofs.spindle]),loose:force(overlap.middle,p.data.qvel[dofs.loose])};
 };
 const xml=`<mujoco><compiler angle="radian"/><option timestep="${timestep}" gravity="0 -${g.gravity} 0" integrator="implicitfast" solver="Newton" iterations="100" tolerance="1e-10"/><default><geom contype="0" conaffinity="0"/><site size=".01"/><equality solref=".002 1" solimp=".9999 .9999 .001"/></default><worldbody><body name="rotor" pos="0 ${g.topY} 0"><joint name="spindle" axis="0 1 0"/><inertial pos="0 0 0" mass=".2" diaginertia=".05 .05 .05"/>${arms}<body name="sleeve" pos="0 ${g.sleeveY-g.topY} 0"><joint name="sleeve" type="slide" axis="0 1 0" damping=".1"/><inertial pos="0 0 0" mass="${g.sleeveMass}" diaginertia=".001 .001 .001"/><site name="left-sleeve" pos="-${g.sleeveRadius} 0 0"/><site name="right-sleeve" pos="${g.sleeveRadius} 0 0"/></body></body>${lever}${beltBodies}</worldbody>${pairs}<equality>${constraints}</equality>${spindleDrive?'<actuator><position joint="spindle" kp="10000" kv="100"/></actuator>':''}</mujoco>`;
 let dofs;const names=['spindle','left-spread','left-link','right-spread','right-link','sleeve',...(linkage?['collar','radial-slide','bell','rod','fork']:[]),...(belt&&linkage?['loose','belt-travel']:[])];
 const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{dofs=Object.fromEntries(names.map(n=>[n,model.jnt_dofadr[id('mjOBJ_JOINT',n)]]));if(spindleDrive)data.qvel[dofs.spindle]=nominalSpeed;},beforeStep:({data,time})=>{const f=beltForces();if(f){data.qfrc_applied[dofs.spindle]=-g.pulleyRadius*f.fast;data.qfrc_applied[dofs.loose]=-g.pulleyRadius*f.loose;data.qfrc_applied[dofs['belt-travel']]=f.fast+f.loose;}if(spindleDrive){const d=drive(time-timestep);data.ctrl[0]=d.angle+.01*d.speed;}}});
 const sitePairs=[['left-end','left-sleeve'],['right-end','right-sleeve'],...(linkage?[['groove','bell-follower'],['rod-end','fork-end']]:[])].map(pair=>pair.map(n=>p.id('mjOBJ_SITE',n)));
 return Object.assign(p,{geometry:g,description:{movement:163,timestep,period,speedAmplitude,spindleDrive,linkage,loadScale,ballContact,belt,beltFriction,beltNormalForce,beltLoad,nominalSpeed,extraPotentialSlope:extraSlope,assumptions:'Source-sized ideal hinges and collar bearing; cranked fork slides radially in an annular sleeve groove. Inferred masses, damping and depths. Reduced finite-width belt contact: regularized Coulomb traction with equal opposite pulley reactions, inferred tension and load. Belt axial shape follows the fork; belt bending, axial friction, remote gearing and hydraulic feedback are not modeled.'},state:()=>{
  mujoco.mj_kinematics(p.model,p.data);const q=n=>p.data.qpos[dofs[n]],position=id=>Array.from(p.data.site_xpos.slice(3*id,3*id+3));
  return{time:p.data.time,spindle:q('spindle'),speed:p.data.qvel[dofs.spindle],leftSpread:g.initialSpread+q('left-spread'),rightSpread:g.initialSpread+q('right-spread'),sleeveY:g.sleeveY+q('sleeve'),...(linkage?{bellAngle:q('bell'),rodAngle:q('bell')+q('rod'),followerX:q('radial-slide'),forkY:nominal.forkY+q('fork'),collarError:q('collar')-q('sleeve')}:{}),...(belt&&linkage?{beltDistance:q('belt-travel'),beltSpeed:p.data.qvel[dofs['belt-travel']],looseAngle:q('loose'),looseSpeed:p.data.qvel[dofs.loose],beltForces:beltForces()}:{}),connectionErrors:sitePairs.map(([a,b])=>Math.hypot(...position(a).map((x,i)=>x-position(b)[i]))),qpos:Array.from(p.data.qpos),qvel:Array.from(p.data.qvel)};
 }});
}
