import profile from '../data/opposed-arm-profile.js';
import {makeOpposedArmGeometry} from './opposed-arm-geometry.js';
import {sampleOpposedArmMotion} from './opposed-arm-motion.js';

export function makeOpposedArmDrive(){
 const model=makeOpposedArmGeometry(profile.geometry),u=model.root.userData;
 Object.assign(u,{profile,reconstructionStatus:'rebuilt',playbackPeriod:profile.playbackPeriod,
  animationTiming:{authoredCyclePeriod:profile.playbackPeriod},minimumDisplayCycleSeconds:profile.playbackPeriod,
  sampledMotionBounds:profile.motionBounds,stateAtTime:sampleOpposedArmMotion,
  qualification:'Measured joint centers and rim circles follow the engraving. The two pawls share one ideal blade (two circular arcs) on radial hinges at the drawn pivots, in place of the engraving\'s unequal hand-drawn pair. The 33 regular axial ratchet teeth, axial layers and radial journals reconstruct details that the source does not fully specify.',
  idealConstraints:'A prescribed horizontal slider drives two fixed-length rods and independent radial arms. Kinematic playback generated by scripts/generate-opposed-arm-kinematics.mjs: each pawl falls under gravity onto the crown teeth and rests at the deepest tilt its rendered outline allows; a pawl moving clockwise slides down the ramp into the root and pushes the vertical face, setting the wheel going at the arm\'s speed; between pushes the wheel coasts against constant friction (0.035 rad/s^2). The friction and the fall rate are reconstruction assumptions; inertia is not otherwise simulated. The eight-second physical cycle plays in four seconds. Startup is retained; the steady wheel advances three teeth clockwise per cycle, standing still for about 2% of it.'});
 model.update=time=>{const state=sampleOpposedArmMotion(time);u.setState(state);Object.assign(u.kinematics,state);};
 model.update(0);return model;
}
