import { chromium } from '@playwright/test';
const b = await chromium.launch({channel:'chrome'});
const p = await b.newPage({viewport:{width:1440,height:1000}});
p.on('pageerror',e=>console.log('PAGEERR',e.message));
p.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text())});
await p.emulateMedia({reducedMotion:'reduce'});
await p.goto('http://127.0.0.1:43917/portable/#/movement/'+process.argv[2]);
await p.locator('.simulation-canvas').waitFor({timeout:30000});
await p.waitForTimeout(1500);
console.log(await p.locator('.simulation-toolbar').innerHTML());
console.log('notes:', await p.locator('.movement-notes').innerText());
await p.screenshot({path:'/tmp/p99-'+process.argv[2]+'.png'});
await b.close();
