import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');
export function makeCascadedTraversePhysics(mujoco,visual,{timestep=.001,period=4,contactTime=.002,friction=0,load=0}={}){
 if(![timestep,period,contactTime].every(v=>Number.isFinite(v)&&v>0)||!Number.isFinite(friction)||friction<0||!Number.isFinite(load))throw new RangeError('Invalid 125 physics options');
 const u=visual.root.userData,f=u.profile,names=Object.keys(f.position),mass=Object.fromEntries(names.map(n=>[n,rigidFamilyInertia(u.parts,u.families,n)])),density=1/mass.right.volume,assets=[],groups={};
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const geoms=(name,mask,other)=>u.cells[name].map((cell,i)=>{const id=name+i;groups[id]=name;assets.push(`<mesh name="${id}" vertex="${vec(cell.flat())}"/>`);return `<geom name="${id}" type="mesh" mesh="${id}" contype="${mask}" conaffinity="${other}"/>`;}).join('');
 const contacts={left:geoms('leftGear',1,2),middle:geoms('middleGear',2,5),right:geoms('rightGear',4,2)};
 const site=(name,p)=>`<site name="${name}" pos="${vec([...p,0])}"/>`,joint=n=>`<joint name="${n}" axis="0 0 1" damping=".001"/>`;
 const rod=n=>`<body name="${n}">${joint(n)}${inertia(n)}${site(n+'End',f.rodEnds[n])}</body>`;
 const gears=['left','middle','right'].map(n=>`<body name="${n}" pos="${vec([...f.centers[n],0])}">${joint(n)}${inertia(n)}${contacts[n]}<body name="${n}Rod" pos="${vec([...f.cranks[n],0])}">${joint(n+'Rod')}${inertia(n+'Rod')}${site(n+'RodEnd',f.rodEnds[n+'Rod'])}</body></body>`).join('');
 const pins=n=>['LeftPin','RightPin'].map(p=>site(n+p,f.linkPins[n+p])).join('');
 const xml=`<mujoco model="125 cascaded geared traverse"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="discrete" solver="Newton" iterations="80" tolerance="1e-10" cone="elliptic"><flag multiccd="disable" diagexact="enable"/></option><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp=".99 .999 .001"/><equality solref=".002 1" solimp=".999 .9999 .0001"/></default><asset>${assets.join('')}</asset><worldbody>${gears}<body name="lower" pos="${vec([...f.position.lower,0])}"><joint name="lowerSlide" type="slide" axis="0 1 0" damping=".01"/>${joint('lower')}${inertia('lower')}${pins('lower')}${rod('transferRod')}</body><body name="slider" pos="${vec([...f.position.slider,0])}"><joint name="slider" type="slide" axis="0 1 0" damping=".01"/>${inertia('slider')}<body name="upper">${joint('upper')}${inertia('upper')}${pins('upper')}</body></body></worldbody><equality><connect site1="middleRodEnd" site2="lowerLeftPin"/><connect site1="rightRodEnd" site2="lowerRightPin"/><connect site1="leftRodEnd" site2="upperLeftPin"/><connect site1="transferRodEnd" site2="upperRightPin"/></equality><actuator><position name="input" joint="right" kp="10000" kv="200"/></actuator></mujoco>`;
 const omega=2*Math.PI/period,input=time=>({position:omega*(time-.25*(1-Math.exp(-time/.25))),velocity:omega*(1-Math.exp(-time/.25))});
 const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{data.qfrc_applied[model.jnt_dofadr[id('mjOBJ_JOINT','slider')]]=load;},beforeStep:({data,time})=>{const q=input(time);data.ctrl[0]=q.position+.02*q.velocity;}});
 const joints=Object.fromEntries([...names,'lowerSlide'].map(n=>{const id=p.id('mjOBJ_JOINT',n);return[n,{q:p.model.jnt_qposadr[id],v:p.model.jnt_dofadr[id]}];}));
 return Object.assign(p,{joints,bodies:Object.fromEntries(names.map(n=>[n,p.id('mjOBJ_BODY',n)])),geomGroups:Object.fromEntries(Object.entries(groups).map(([id,name])=>[p.id('mjOBJ_GEOM',id),name])),description:{xml,mass,density,input,options:{timestep,period,contactTime,friction,load},assumptions:'Only the right gear is actuated. Native involute tooth contacts drive the other gears. Four ideal pin connections close the two passive linkage stages. Both central pins have inferred vertical guides, following the modern reference interpretation. Measured crank pins and unequal rod/link dimensions are retained. Gear counts 19:23:29, regular coaxial axes, hidden axial depths, uniform density, bearings and input timing are reconstruction assumptions. No passive gear angle, rod angle or output travel is prescribed.'}});
}
