import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {createAuthoredDoorCloserMovement} from '../src/simulation/authored-door-closers.js';
import {solidSurface,surfacePoints} from './helpers/solid-surface.mjs';
const m=createAuthoredDoorCloserMovement({id:385}),d=m.root.userData,b=d.blocks,w=d.workingJoints,cache=new Map();
const get=o=>{if(!cache.has(o))cache.set(o,{points:surfacePoints(o.geometry),surface:solidSurface(o.geometry)});return cache.get(o);};
const find=name=>{let result;m.root.traverse(o=>{if(o.userData.role===name)result=o;});return result;};
function gap(a,b){let result=Infinity;for(const[x,y]of[[a,b],[b,a]]){const transform=y.matrixWorld.clone().invert().multiply(x.matrixWorld),surface=get(y).surface;for(const p of get(x).points){const q=p.clone().applyMatrix4(transform);if(surface.box.distanceToPoint(q)>.006)continue;result=Math.min(result,surface.signedDistance(q,.3));}}return result;}
function sweep(pairs,steps=96){let worst=Infinity;for(let i=0;i<=steps;i++){m.update(10*i/steps);m.root.updateMatrixWorld(true);for(const[a,b]of pairs){const v=gap(a,b);worst=Math.min(worst,v);assert.ok(v>-.000002,`${i}: ${a.userData.role}/${b.userData.role}: ${v}`);}}return worst;}
test('385 both actual through-bored sockets clear their rotating pins for the full cycle',()=>{sweep(w.forks.map(f=>[f.socket,f.verticalPin]));for(const f of w.forks){assert.equal(get(f.socket).surface.inside(new T.Vector3()),false);assert.equal(get(f.socket).surface.inside(new T.Vector3(.14,0,0)),true);}});
test('385 socket forks carry transverse pins through the real outer link eyes',()=>{const pairs=[];w.forks.forEach((f,i)=>{for(const e of f.ears)pairs.push([e,f.jointPin],[e,w.links[i]]);pairs.push([w.links[i],f.jointPin],[w.links[i],f.bridge],[w.links[i],f.verticalPin],[w.links[i],f.socket]);});sweep(pairs);for(let i=0;i<=32;i++){m.update(10*i/32);m.root.updateMatrixWorld(true);w.forks.forEach((f,j)=>{const eye=w.links[j].localToWorld(new T.Vector3()),axis=f.jointPin.worldToLocal(eye);assert.ok(Math.hypot(axis.x,axis.y)<1e-12);assert.ok(Math.abs(axis.z)<.155-.04);});}});
test('385 central hinge has separate rigid link and suspension layers captured on a real axle',()=>{sweep([[w.links[0],w.links[1]],[w.links[0],w.links[2]],[w.links[1],w.links[2]],...w.links.map(o=>[o,w.centerPin]),...w.links.flatMap(o=>w.centerCaps.map(c=>[o,c]))]);for(let i=0;i<=32;i++){m.update(10*i/32);m.root.updateMatrixWorld(true);for(const[j,link]of w.links.entries()){const q=link.localToWorld(new T.Vector3(j===2?0:d.geometry.linkLength,0,0));q.applyMatrix4(w.centerPin.matrixWorld.clone().invert());assert.ok(Math.hypot(q.x,q.y)<2e-12);assert.ok(Math.abs(q.z)<.105);}}});
test('385 suspension clears the weight eye, neck and body while the finite pin spans both eyes',()=>{sweep([[w.links[2],b.weightEye],[w.links[2],b.weightBody],[w.links[2],find('weight-neck')],[w.links[2],w.weightPin],[b.weightEye,w.weightPin],[w.links[2],w.weightCap]]);for(let i=0;i<=16;i++){m.update(10*i/16);m.root.updateMatrixWorld(true);const end=w.links[2].localToWorld(new T.Vector3(d.geometry.weightSuspensionLength,0,0));const q=w.weightPin.worldToLocal(end);assert.ok(Math.hypot(q.x,q.y)<1e-12);assert.ok(Math.abs(q.z)<.145-.0175);}});
test('385 shafts and forks remain supported without hanging bearing bridges',()=>{m.update(0);m.root.updateMatrixWorld(true);for(const f of w.forks){const pinBox=new T.Box3().setFromObject(f.verticalPin),bridgeBox=new T.Box3().setFromObject(f.bridge);assert.ok(pinBox.intersectsBox(bridgeBox));for(const ear of f.ears)assert.ok(new T.Box3().setFromObject(ear).intersectsBox(bridgeBox));}});
test('385 retains analytic gravity law and buffers and discloses current source/timing limits',()=>{const before=[];m.root.traverse(o=>before.push([o,o.geometry]));for(let i=0;i<100;i++){m.update(i*.1);const s=d.kinematics;assert.ok(Math.abs(s.apex.distanceTo(s.frameAnchor)-d.geometry.linkLength)<1e-12);assert.ok(Math.abs(s.apex.distanceTo(s.doorAnchor)-d.geometry.linkLength)<1e-12);assert.ok(s.closingTorque<=1e-12);}const after=[];m.root.traverse(o=>after.push([o,o.geometry]));assert.deepEqual(before,after);assert.equal(d.minimumDisplayCycleSeconds,10);assert.equal(d.hideGround,true);assert.equal(d.sourceAnimation.available,true);assert.equal(d.sourceAnimation.officialCanvasModelPresent,true);assert.equal(d.sourceAnimation.officialCanvasModelId,'mm_385');assert.match(d.reconstructionNote,/prescribed/);assert.match(d.reconstructionNote,/not simulated/);});
