import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {createAuthoredDoorCloserMovement} from '../src/simulation/authored-door-closers.js';
import {solidSurface,surfacePoints} from './helpers/solid-surface.mjs';
const m=createAuthoredDoorCloserMovement({id:385}),d=m.root.userData,b=d.blocks,w=d.workingJoints,cache=new Map();
const get=o=>{if(!cache.has(o))cache.set(o,{points:surfacePoints(o.geometry),surface:solidSurface(o.geometry)});return cache.get(o);};
const find=name=>{let result;m.root.traverse(o=>{if(o.userData.role===name)result=o;});return result;};
function gap(a,b){let result=Infinity;for(const[x,y]of[[a,b],[b,a]]){const transform=y.matrixWorld.clone().invert().multiply(x.matrixWorld),surface=get(y).surface;for(const p of get(x).points){const q=p.clone().applyMatrix4(transform);if(surface.box.distanceToPoint(q)>.006)continue;result=Math.min(result,surface.signedDistance(q,.3));}}return result;}
function sweep(pairs,steps=96){let worst=Infinity;for(let i=0;i<=steps;i++){m.update(10*i/steps);m.root.updateMatrixWorld(true);for(const[a,b]of pairs){const v=gap(a,b);worst=Math.min(worst,v);assert.ok(v>-.000002,`${i}: ${a.userData.role}/${b.userData.role}: ${v}`);}}return worst;}
test('385 both actual through-bored sockets clear their rotating pins for the full cycle',()=>{sweep(w.forks.map(f=>[f.socket,f.verticalPin]));for(const f of w.forks){assert.equal(get(f.socket).surface.inside(new T.Vector3()),false);assert.equal(get(f.socket).surface.inside(new T.Vector3(.14,0,0)),true);}});
test('385 plain pin eyes carry transverse pins through the real link eyes (no clevis)',()=>{const pairs=[];w.forks.forEach((f,i)=>{assert.equal(f.ears.length,1);assert.equal(f.bridge,undefined);for(const e of f.ears)pairs.push([e,f.jointPin],[e,w.links[i]]);pairs.push([w.links[i],f.jointPin],[w.links[i],f.verticalPin],[w.links[i],f.socket]);});sweep(pairs);for(let i=0;i<=32;i++){m.update(10*i/32);m.root.updateMatrixWorld(true);w.forks.forEach((f,j)=>{const eye=w.links[j].localToWorld(new T.Vector3()),axis=f.jointPin.worldToLocal(eye);assert.ok(Math.hypot(axis.x,axis.y)<1e-12);assert.ok(Math.abs(axis.z)<.10-.04);});}});
test('385 central hinge carries both link eyes on one short axle',()=>{assert.equal(w.links.length,2);assert.equal(w.centerCaps.length,0);sweep([[w.links[0],w.links[1]],...w.links.map(o=>[o,w.centerPin])]);for(let i=0;i<=32;i++){m.update(10*i/32);m.root.updateMatrixWorld(true);for(const link of w.links){const q=link.localToWorld(new T.Vector3(d.geometry.linkLength,0,0));q.applyMatrix4(w.centerPin.matrixWorld.clone().invert());assert.ok(Math.hypot(q.x,q.y)<2e-12);assert.ok(Math.abs(q.z)<.105);}}});
test('385 S-hook hangs the weight from the apex pin in the link plane and threads the weight eye',()=>{assert.equal(b.suspension.visible,false);sweep([[w.hook,b.weightEye],[w.hook,b.weightBody],[w.hook,find('weight-neck')],[w.hook,w.centerPin],...w.links.map(o=>[w.hook,o])]);for(let i=0;i<=16;i++){m.update(10*i/16);m.root.updateMatrixWorld(true);const box=new T.Box3().setFromObject(w.hook),apex=d.kinematics.apex;assert.ok(box.max.y>apex.y+.1&&box.max.y<apex.y+.15,'hook wraps over the apex pin');const c=box.getCenter(new T.Vector3());assert.ok(Math.hypot(c.x-apex.x,c.z-apex.z)<.12,'hook hangs under the apex');}});
test('385 pin eyes are part of their vertical pins',()=>{m.update(0);m.root.updateMatrixWorld(true);for(const f of w.forks){const pinBox=new T.Box3().setFromObject(f.verticalPin);for(const ear of f.ears)assert.ok(new T.Box3().setFromObject(ear).intersectsBox(pinBox));}});
test('385 retains analytic gravity law and buffers and discloses current source/timing limits',()=>{const before=[];m.root.traverse(o=>before.push([o,o.geometry]));for(let i=0;i<100;i++){m.update(i*.1);const s=d.kinematics;assert.ok(Math.abs(s.apex.distanceTo(s.frameAnchor)-d.geometry.linkLength)<1e-12);assert.ok(Math.abs(s.apex.distanceTo(s.doorAnchor)-d.geometry.linkLength)<1e-12);assert.ok(s.closingTorque<=1e-12);}const after=[];m.root.traverse(o=>after.push([o,o.geometry]));assert.deepEqual(before,after);assert.equal(d.minimumDisplayCycleSeconds,10);assert.equal(d.hideGround,true);assert.equal(d.sourceAnimation.available,true);assert.equal(d.sourceAnimation.officialCanvasModelPresent,true);assert.equal(d.sourceAnimation.officialCanvasModelId,'mm_385');assert.match(d.reconstructionNote,/prescribed/);assert.match(d.reconstructionNote,/not simulated/);});
