import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import{createAuthoredFrictionClutchMovement as a}from '../src/simulation/authored-friction-clutches.js';
import{createAuthoredFrictionWindlassMovement as b}from '../src/simulation/authored-friction-windlasses.js';
import{createAuthoredAdjustableFrictionGearMovement as c}from '../src/simulation/authored-adjustable-friction-gears.js';
import {solidSurface,surfacePoints} from './helpers/solid-surface.mjs';
const models=[a({id:267}),b({id:280}),c({id:413})],cache=new Map();
const get=o=>{if(!cache.has(o))cache.set(o,{p:surfacePoints(o.geometry),s:solidSurface(o.geometry)});return cache.get(o);};
function clearance(a,b){let min=Infinity;for(const[x,y]of[[a,b],[b,a]]){const tr=y.matrixWorld.clone().invert().multiply(x.matrixWorld),s=get(y).s;for(const p of get(x).p){const q=p.clone().applyMatrix4(tr);if(s.box.distanceToPoint(q)>.003)continue;min=Math.min(min,s.signedDistance(q,.15));}}return min;}
function sweep(m,pairs,period,steps=64,tolerance=2e-6){for(let i=0;i<=steps;i++){m.update(period*i/steps);m.root.updateMatrixWorld(true);for(const[a,b]of pairs)assert.ok(clearance(a,b)>-tolerance,`${i}: ${a.userData.role}/${b.userData.role}`);}}
const inside=(o,p)=>get(o).s.inside(o.worldToLocal(p.clone()));

test('267 real arm faces meet the rim and clear it throughout prescribed retraction',()=>{const m=models[0],b=m.root.userData.blocks,pairs=b.arms.map(o=>[o.children[0],b.rim]);sweep(m,pairs,9.2);m.update(2);m.root.updateMatrixWorld(true);for(const[a,b]of pairs)assert.ok(clearance(a,b)<4e-5,'finite engaged face, not a zero-size point law');m.update(6);m.root.updateMatrixWorld(true);for(const arm of b.arms){const p=arm.localToWorld(new T.Vector3(...m.root.userData.geometry.tipOuterRelative.toArray(),0));const q=b.rim.worldToLocal(p);assert.ok(Math.hypot(q.x,q.y)<1.95,'released arm retracts inside rim');}});
test('267 pivot journals clear and shaft collar actually connects the carrier',()=>{const m=models[0],b=m.root.userData.blocks;sweep(m,b.arms.map((o,i)=>[o.children[0],b.pivotBosses[i]]),9.2);m.update(0);m.root.updateMatrixWorld(true);const p=b.carrierRotor.localToWorld(new T.Vector3(.35,0,.12));assert.ok(inside(b.carrier,p)&&inside(b.carrierCollar,p));});
test('280 shoe and both inner flanges fit the finite rim during the moving-jaw stroke',()=>{const m=models[1],b=m.root.userData.blocks;sweep(m,[[b.clampShoe,b.outerRim],[b.shortLeverBody,b.outerRim],...b.jawFlanges.map(o=>[o,b.outerRim])],4,64,1.2e-5);m.update(1.3);m.root.updateMatrixWorld(true);assert.ok(clearance(b.clampShoe,b.outerRim)<4e-5);for(const flange of b.jawFlanges)assert.ok(Math.abs(clearance(flange,b.outerRim))<4e-5);});
test('280 independent pivot, coupler and jaw/web neighbours remain clear',()=>{const m=models[1],b=m.root.userData.blocks;sweep(m,[[b.shortLeverBody,b.shortLeverPivotPin],[b.shortLeverBody,b.jawPivotBridge],[b.shortLeverBody,b.frontJawJournal],[b.shortLeverBody,b.lowerLinkPin],[b.finiteCoupler,b.lowerLinkPin],[b.finiteCoupler,b.upperLinkPin],...b.jawCheeks.flatMap(o=>[[o,b.outerRim],[o,b.wheelDisk],[o,b.ratchetCarrier]])],4);});
test('280 jaw flanges, cheeks and separated journals form one connected casting',()=>{const m=models[1],b=m.root.userData.blocks,P=m.root.userData.geometry.movingJawPivotRadius;m.update(0);m.root.updateMatrixWorld(true);for(const[i,side]of[-1,1].entries()){const flange=b.jawFlanges[i],cheek=b.jawCheeks[i],journal=i?b.frontJawJournal:b.jawPivotBridge;for(const[a,c,p]of[[flange,cheek,new T.Vector3(m.root.userData.geometry.wheelInnerRadius-.06,0,side*.43)],[cheek,journal,new T.Vector3(P+.20,0,side*.43)]]){const world=b.movingJaw.localToWorld(p);assert.ok(inside(a,world)&&inside(c,world));}}});
test('413 actual male/female helical threads and bored hardware clear during rotation and advance',()=>{const m=models[2],b=m.root.userData.blocks;sweep(m,[[b.threadedEnd,b.internalThread],[b.threadedEnd,b.nutBody],[b.threadedEnd,b.nutHandle],[b.upperShaft,b.internalThread],[b.leftClampPlate,b.threadedEnd]],9,12);const p=m.root.userData.threadProfiles;assert.equal(p.external.lead,p.internal.lead);assert.ok(p.external.outer>p.internal.inner,'flanks overlap radially to transmit axial load');});
test('413 unloaded V profiles mate; free expansion remains an explicit compliance residual',()=>{const m=models[2],b=m.root.userData.blocks;m.update(0);m.root.updateMatrixWorld(true);for(const[a,c]of[[b.leftRubberHalf,b.lowerLeftHalf],[b.rightRubberHalf,b.lowerRightHalf]])assert.ok(clearance(a,c)>-2e-6);m.update(2);m.root.updateMatrixWorld(true);const penetration=Math.min(clearance(b.leftRubberHalf,b.lowerLeftHalf),clearance(b.rightRubberHalf,b.lowerRightHalf));assert.ok(penetration<-.02&&penetration>-.09);assert.match(m.root.userData.workingPartsReview.qualification,/not a validated deformation/);console.log({rubberFreeExpansionResidual:penetration});});
test('family presentation retains buffers and disables fog/ground',()=>{for(const m of models){const before=[];m.root.traverse(o=>before.push([o,o.geometry]));for(let i=0;i<=32;i++)m.update(i/8);const after=[];m.root.traverse(o=>after.push([o,o.geometry]));assert.deepEqual(before,after);assert.equal(m.root.userData.hideGround,true);}});

test('280 finite pawls overrun CCW, drop into the root and seat on the locking face after the backlash slip',()=>{const m=models[1],b=m.root.userData.blocks,parts=[b.upperPawl,b.lowerPawl].map(p=>p.children.find(o=>o.userData.role==='bored-holding-pawl-arm'));assert.equal(b.upperPawlTip.visible||b.lowerPawlTip.visible,false,'no ball tips');let worst=Infinity;const pawlTooth=(pawl)=>{let g=Infinity;for(const tooth of b.ratchetTeeth){const box=get(pawl).s.box.clone().applyMatrix4(pawl.matrixWorld);if(!box.intersectsBox(get(tooth).s.box.clone().applyMatrix4(tooth.matrixWorld)))continue;g=Math.min(g,clearance(pawl,tooth));}return g;};
 for(let i=0;i<=128;i++){m.update(8*i/128);m.root.updateMatrixWorld(true);for(const pawl of parts){const gap=pawlTooth(pawl);worst=Math.min(worst,gap);assert.ok(gap>-2e-6,`${i} ${pawl.userData.role}: ${gap}`);}}
 // Holds: the upper pawl at the start of even strokes, the lower at odd ones; each nose sits in its root against the locking face.
 for(const[t,index]of[[0,0],[4,1],[8,0],[12,1]]){m.update(t);m.root.updateMatrixWorld(true);const key=index?'lowerHoldingPawl':'upperHoldingPawl';assert.ok(m.root.userData.contacts[key].active,`${t} ${key} seated`);const gap=pawlTooth(parts[index]);assert.ok(gap<.005,`${t} seated face gap ${gap} (surface-sample spacing)`);}
 // Backlash: after the stroke the wheel stands past the hold, then slips back by exactly the overshoot.
 const g=m.root.userData.geometry,d=m.root.userData;const top=d.stateAtTime(2.3).wheelAngle,held=d.stateAtTime(3).wheelAngle;assert.ok(top-held>.004&&top-held<.01);assert.ok(Math.abs(held-g.outputStopPitch)<1e-9);
 const tooth=b.ratchetTeeth[0].geometry.userData.plate.polygons[0][0],a=tooth[0],c=tooth[1];assert.ok(c[0]>a[0]&&Math.abs(c[1]-a[1])<1e-10,'steep radial locking face has outward -Y normal, opposing clockwise advance');
 for(const t of[0,8,16]){m.update(t-1e-8);const before=[b.upperPawl.rotation.z,b.lowerPawl.rotation.z];m.update(t+1e-8);assert.ok(Math.abs(before[0]-b.upperPawl.rotation.z)<1e-6&&Math.abs(before[1]-b.lowerPawl.rotation.z)<1e-6,'no phase-boundary teleport');}assert.match(d.backstopReview.playback,/no load/);console.log({backstopMinimumGap:worst});});