import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import{createAuthoredIntermittentMovement as make}from '../src/simulation/authored-intermittent.js';
import{solidSurface,surfacePoints}from './helpers/solid-surface.mjs';
const models=[make({id:212}),make({id:215})],cache=new Map();
function data(o){if(!cache.has(o)){const all=surfacePoints(o.geometry),step=Math.max(1,Math.floor(all.length/2400));cache.set(o,{s:solidSurface(o.geometry),p:all.filter((_,i)=>i%step===0)});}return cache.get(o);}
function gap(a,b){let min=Infinity;for(const[x,y]of[[a,b],[b,a]]){const tr=y.matrixWorld.clone().invert().multiply(x.matrixWorld),s=data(y).s;for(const p of data(x).p){const q=p.clone().applyMatrix4(tr);if(s.box.distanceToPoint(q)>.002)continue;min=Math.min(min,s.signedDistance(q,.4));}}return min;}
const distance=(o,world)=>data(o).s.distance(o.worldToLocal(world.clone()));
function pose(m,travel){const d=m.root.userData,s=d.stateAtInputTravel(travel,0,0),b=d.blocks;b.driver.userData.rotor.rotation.z=s.driverAngle;b.stopWheel.userData.rotor.rotation.z=s.stopWheelAngle;m.root.updateMatrixWorld(true);return s;}
test('215 actual solids fit indexing, mouth handoff, terminal stops and dwells',()=>{const m=models[1],d=m.root.userData,b=d.blocks,g=d.geometry,poses=Array.from({length:65},(_,i)=>g.reverseInputLimit+(g.forwardInputLimit-g.reverseInputLimit)*i/64);for(const x of[0,Math.PI/6,Math.PI/3,Math.PI,2*Math.PI,2*Math.PI+Math.PI/6,g.reverseInputLimit,g.forwardInputLimit])poses.push(x);for(const u of poses){const state=pose(m,u),phase=((u%(2*Math.PI))+2*Math.PI)%(2*Math.PI);for(const[a,c]of[[b.facePin,b.stopWheelBody],[b.lockingCamBody,b.stopWheelBody],[b.driverBody,b.stopWheelBody]])assert.ok(gap(a,c)>-2.2e-5,`${u}: ${a.userData.role}/${c.userData.role}: ${gap(a,c)}`);}assert.equal(b.lockingCamBody.geometry.parameters.options.bevelEnabled,false);assert.equal(b.stopWheelBody.geometry.parameters.options.bevelEnabled,false);});
test('215 finite pin retains both radial slot walls as real load faces',()=>{const m=models[1],d=m.root.userData,b=d.blocks,g=d.geometry;for(let i=1;i<24;i++){const s=pose(m,Math.PI/3*i/24),p=s.engagement.pinInStopWheelLocal,n=new T.Vector2(-p.y,p.x).normalize();for(const side of[-1,1]){const contact=b.stopWheel.userData.rotor.localToWorld(new T.Vector3(p.x+side*g.pinRadius*n.x,p.y+side*g.pinRadius*n.y,0));assert.ok(distance(b.stopWheelBody,contact)<2e-6,'slot wall witness');assert.ok(distance(b.facePin,contact)<5.5e-5,'actual pin circumference witness');}}});
test('215 both terminal contacts remain on working surfaces and block further driver travel',()=>{const m=models[1],d=m.root.userData,b=d.blocks,g=d.geometry;for(const [u,sign]of[[g.forwardInputLimit,-1],[g.reverseInputLimit,1]]){const s=pose(m,u),contact=s.limit.stopContact.contactPoint,world=new T.Vector3(contact.x,contact.y,0);assert.ok(distance(b.lockingCamBody,world)<3e-6,'cusp remains present');assert.ok(distance(b.stopWheelBody,world)<2.2e-5,'terminal sector remains present');b.driver.userData.rotor.rotation.z+=sign*.002;m.root.updateMatrixWorld(true);assert.ok(gap(b.lockingCamBody,b.stopWheelBody)<-.0002,'overtravel crosses actual working face');}});
test('212 circular dwell faces fit and its corrected branches state impact and loading limits',()=>{const m=models[0],d=m.root.userData,b=d.blocks;for(const t of[2.5,6.4,10.3]){m.update(t);m.root.updateMatrixWorld(true);assert.ok(gap(b.driverBody,b.stopWheelBody)>-3e-6,'dense circular locking profiles');}assert.match(d.reconstructionNote,/own pushing contact faces/);assert.match(d.reconstructionNote,/impacts/);assert.match(d.reconstructionNote,/not simulated/);});
test('212 and215 fixed support plates contain real through-bores around the rotating shafts',()=>{for(const m of models){const d=m.root.userData,b=d.blocks;for(let i=0;i<17;i++){m.update(d.timeline.demonstrationPeriod*i/16);m.root.updateMatrixWorld(true);for(const[j,support]of d.workingSupports.entries()){const shaft=j===0?b.driverShaft:b.stopWheelShaft;let axis;shaft.traverse(o=>{if(o.geometry&&!axis)axis=o;});assert.ok(gap(support,axis)>-2e-6);assert.equal(data(support).s.inside(new T.Vector3()),false);assert.equal(data(support).s.inside(new T.Vector3(.15,0,0)),true);}}}});
test('both models retain geometry and qualify prescribed driving and continuous reverse playback',()=>{for(const m of models){const d=m.root.userData,before=[];m.root.traverse(o=>before.push([o,o.geometry]));for(let i=0;i<33;i++)m.update(d.timeline.demonstrationPeriod*i/32);const after=[];m.root.traverse(o=>after.push([o,o.geometry]));assert.deepEqual(before,after);assert.equal(d.hideGround,true);assert.ok(d.minimumDisplayCycleSeconds>=14);assert.equal(d.sourceAnimation.available,true);assert.ok(d.reconstructionNote.length>50);}});

test('215 former mouth collision is removed and selected-force assumptions are disclosed',t=>{const m=models[1],d=m.root.userData,b=d.blocks;pose(m,-5.199966088277341);const residual=gap(b.facePin,b.stopWheelBody);t.diagnostic(`source-mouth witness signed clearance: ${residual}`);assert.ok(residual>-2.2e-5,'former collision clears finite surfaces');assert.match(d.reconstructionNote,/assisting preload/);assert.match(d.reconstructionNote,/loading remain prescribed/);});
