import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {createAuthoredIntermittentMovement as make} from '../src/simulation/authored-intermittent.js';
import {solidSurface,surfacePoints} from './helpers/solid-surface.mjs';
const m=make({id:232}),d=m.root.userData,b=d.blocks,g=d.geometry,cache=new Map(),wheel=b.wheel.userData.body;
let shaft; b.outputShaft.traverse(o=>{if(o.isMesh&&!shaft)shaft=o;});
function data(o){if(!cache.has(o)){const points=surfacePoints(o.geometry),stride=Math.max(1,Math.floor(points.length/2000));cache.set(o,{surface:solidSurface(o.geometry),points:points.filter((_,i)=>i%stride===0)});}return cache.get(o);}
function gap(a,b){let minimum=Infinity;for(const[x,y]of[[a,b],[b,a]]){const matrix=y.matrixWorld.clone().invert().multiply(x.matrixWorld),s=data(y).surface;for(const p of data(x).points){const q=p.clone().applyMatrix4(matrix);if(s.box.distanceToPoint(q)>.01)continue;minimum=Math.min(minimum,s.signedDistance(q,.3));}}return minimum;}
function pose(t){m.update(t);m.root.updateMatrixWorld(true);}

test('232 in-plane pawl C clears the actual wheel solid through repeated cycles, touching only at its drawing flank',t=>{let worst=Infinity;for(let i=0;i<=192;i++){pose(2*g.cyclePeriod*i/192);const v=gap(b.pawlBody,wheel);worst=Math.min(worst,v);assert.ok(v>-2e-6,`pawl C at ${i}: ${v}`);}t.diagnostic(`minimum pawl surface clearance ${worst}`);});

test('232 pawl C is one flat plate inside the wheel tooth plane, with no pin or roller reaching the teeth',()=>{pose(0);const wheelBox=new T.Box3().setFromObject(wheel),pawlBox=new T.Box3().setFromObject(b.pawlBody);assert.ok(pawlBox.min.z>=wheelBox.min.z-1e-9&&pawlBox.max.z<=wheelBox.max.z+1e-9);const meshes=[];b.pawl.traverse(o=>{if(o.isMesh&&o.visible)meshes.push(o);});assert.deepEqual(meshes.filter(o=>o!==b.pawlIndex),[b.pawlBody]);assert.equal(b.workingTip,b.pawlBody);});

test('232 selected pin passages are actual clear bores across the four-bar stroke',()=>{for(let i=0;i<=32;i++){pose(g.cyclePeriod*i/32);for(const[a,c]of[[b.pawlBody,b.framePlate],[b.upperPivotPin,wheel],[b.carrierHub,shaft],[b.coupler,b.inputCouplerPin],[b.coupler,b.pawlCouplerPin],[b.inputLeverBody,b.inputCouplerPin],[b.pawlBody,b.pawlCouplerPin],[b.pawlBody,b.upperPivotPin],[b.framePlate,b.upperPivotPin]])assert.ok(gap(a,c)>-2e-6,`${a.userData.role}/${c.userData.role}: ${gap(a,c)}`);}});

test('232 oblong finger keeps a real radial tooth face and clockwise compressive torque throughout draw',t=>{let max=0;for(let i=0;i<=64;i++){pose(g.cyclePeriod*(.62+.3*i/64));const s=d.kinematics,q=s.contact.wheelPoint,world=new T.Vector3(q.x,q.y,0),a=data(wheel).surface.distance(wheel.worldToLocal(world.clone())),c=data(b.workingTip).surface.distance(b.workingTip.worldToLocal(world.clone()));max=Math.max(max,a,c);assert.ok(a<2e-7&&Math.abs(c-g.fingerFaceClearance)<2.1e-5,`${a}/${c}`);assert.ok(q.x*s.contact.surfaceNormal.y-q.y*s.contact.surfaceNormal.x<-(g.drawFaceRadius-.05),'real compressive normal drives clockwise');}t.diagnostic(`maximum actual draw witness distance ${max}`);assert.equal(d.carrierReconstruction.passiveValidated,false);assert.match(d.reconstructionNote,/rocking carrier/);});

test('232 exposed state and geometry ownership stay consistent',()=>{const before=[];m.root.traverse(o=>before.push([o,o.geometry]));for(let i=0;i<=512;i++){const time=g.cyclePeriod*i/512;pose(time);const s=d.stateAtTime(time);assert.equal(d.kinematics.wheelAngle,s.wheelAngle);}const after=[];m.root.traverse(o=>after.push([o,o.geometry]));assert.deepEqual(before,after);assert.equal(d.hideGround,true);assert.ok(d.minimumDisplayCycleSeconds>=6);assert.equal(d.sourceAnimation.available,false);assert.match(d.sourceAnimation.reason,/no canvas/);});

test('232 carrier A carries plain holes: no fixed guide pins, slots or brace',()=>{for(const key of['fixedGuideSupport','frameMountBolt','retainingPivotPin'])assert.equal(b[key],undefined);const roles=[];m.root.traverse(o=>roles.push(o.userData.role??''));assert.ok(!roles.some(r=>/guide-pin|mount-bolt|guide-pin-support/.test(r)));});
