import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {createAuthoredIntermittentMovement as make} from '../src/simulation/authored-intermittent.js';
import {solidSurface,surfacePoints} from './helpers/solid-surface.mjs';
const m=make({id:232}),d=m.root.userData,b=d.blocks,g=d.geometry,cache=new Map(),wheel=b.wheel.userData.body;
let shaft; b.outputShaft.traverse(o=>{if(o.isMesh&&!shaft)shaft=o;});
function data(o){if(!cache.has(o)){const points=surfacePoints(o.geometry),stride=Math.max(1,Math.floor(points.length/2000));cache.set(o,{surface:solidSurface(o.geometry),points:points.filter((_,i)=>i%stride===0)});}return cache.get(o);}
function gap(a,b){let minimum=Infinity;for(const[x,y]of[[a,b],[b,a]]){const matrix=y.matrixWorld.clone().invert().multiply(x.matrixWorld),s=data(y).surface;for(const p of data(x).points){const q=p.clone().applyMatrix4(matrix);if(s.box.distanceToPoint(q)>.01)continue;minimum=Math.min(minimum,s.signedDistance(q,.3));}}return minimum;}
function pose(t){m.update(t);m.root.updateMatrixWorld(true);}

test('232 retaining body and working roller clear actual wheel solids through repeated cycles',t=>{let worst=Infinity;for(let i=0;i<=192;i++){pose(2*g.cyclePeriod*i/192);for(const part of[b.retainingBody,b.retainingNose,b.retainingNoseAxle,b.pawlBody,b.workingTip,b.workingTipAxle]){const v=gap(part,wheel);worst=Math.min(worst,v);assert.ok(v>-2e-6,`${part.userData.role} at ${i}: ${v}`);}}t.diagnostic(`minimum retaining surface clearance ${worst}`);});

test('232 seated roller retains a real face opposing rollback; pre-lift is explicitly prescribed',()=>{for(const t of[0,1,6,7]){pose(t);const q=d.retainingContact.contactPoint,point=new T.Vector3(q.x,q.y,.05);assert.ok(data(wheel).surface.distance(wheel.worldToLocal(point.clone()))<2e-7);assert.ok(data(b.retainingNose).surface.distance(b.retainingNose.worldToLocal(point.clone()))<3e-5);const center=d.kinematics.retainingNosePoint,n=q.clone().sub(center).normalize(),torque=q.x*n.y-q.y*n.x;assert.ok(torque<-1,'compressive force opposes counterclockwise rollback');b.wheel.userData.rotor.rotation.z+=.003;m.root.updateMatrixWorld(true);assert.ok(gap(b.retainingNose,wheel)<-.001,'attempted rollback crosses the actual roller');}assert.equal(d.retainingContact.passiveLiftSolved,false);assert.match(d.reconstructionNote,/click transfer are prescribed/);});

test('232 selected pin passages are actual clear bores across the four-bar stroke',()=>{for(let i=0;i<=32;i++){pose(g.cyclePeriod*i/32);for(const[a,c]of[[b.pawlBody,b.framePlate],[b.pawlBody,b.retainingBody],[b.pawlBody,b.fixedGuideSupport],[b.upperPivotPin,wheel],[b.framePlate,b.fixedGuideSupport],[b.carrierHub,shaft], [b.framePlate,b.frameMountBolt], [b.fixedGuideSupport,b.retainingPivotPin], [b.workingTip,b.workingTipAxle], [b.pawlBody,b.workingTipAxle], [b.coupler,b.inputCouplerPin],[b.coupler,b.pawlCouplerPin],[b.inputLeverBody,b.inputCouplerPin],[b.pawlBody,b.pawlCouplerPin],[b.pawlBody,b.upperPivotPin],[b.framePlate,b.upperPivotPin],[b.framePlate,b.retainingPivotPin],[b.retainingBody,b.retainingPivotPin],[b.retainingBody,b.retainingNoseAxle],[b.retainingNose,b.retainingNoseAxle]])assert.ok(gap(a,c)>-2e-6,`${a.userData.role}/${c.userData.role}: ${gap(a,c)}`);}});

test('232 short tip keeps a real radial tooth face and clockwise compressive torque throughout draw',t=>{let max=0;for(let i=0;i<=64;i++){pose(g.cyclePeriod*(.62+.3*i/64));const s=d.kinematics,q=s.contact.wheelPoint,world=new T.Vector3(q.x,q.y,0),a=data(wheel).surface.distance(wheel.worldToLocal(world.clone())),c=data(b.workingTip).surface.distance(b.workingTip.worldToLocal(world.clone()));max=Math.max(max,a,c);assert.ok(a<2e-7&&c<2.1e-5,`${a}/${c}`);assert.ok(q.x*s.contact.surfaceNormal.y-q.y*s.contact.surfaceNormal.x<-1.8,'real compressive normal drives clockwise');}t.diagnostic(`maximum actual draw witness distance ${max}`);assert.equal(d.carrierReconstruction.passiveValidated,false);assert.match(d.reconstructionNote,/rocking carrier/);});

test('232 continuous click derivatives, exposed state and geometry ownership stay consistent',()=>{const before=[];m.root.traverse(o=>before.push([o,o.geometry]));for(let i=0;i<=512;i++){const time=g.cyclePeriod*i/512;pose(time);const s=d.stateAtTime(time),h=1e-6,a=d.stateAtTime(time-h),z=d.stateAtTime(time+h);assert.ok(Math.abs((z.clickAngle-a.clickAngle)/(2*h)-s.clickAngularSpeed)<1e-6);assert.equal(b.retainingClick.rotation.z,s.clickAngle);assert.equal(d.contacts.retainingClick.engaged,s.retainingClickEngaged);assert.equal(d.kinematics.wheelAngle,s.wheelAngle);}const after=[];m.root.traverse(o=>after.push([o,o.geometry]));assert.deepEqual(before,after);assert.equal(d.hideGround,true);assert.ok(d.minimumDisplayCycleSeconds>=6);assert.equal(d.sourceAnimation.available,false);assert.match(d.sourceAnimation.reason,/no canvas/);});
