import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {createAuthoredFrictionWindlassMovement} from '../src/simulation/authored-friction-windlasses.js';
const model=createAuthoredFrictionWindlassMovement({id:280}),d=model.root.userData,b=d.blocks,g=d.geometry;
const near=(a,c,e=1e-10)=>assert.ok(Math.abs(a-c)<e,`${a} ≠ ${c}`);
test('280 source block travels around the rim and its lever pin is fixed to that block',()=>{assert.equal(b.shortLever.parent,b.movingJaw);assert.equal(b.shortLeverPivotPin.parent,b.movingJaw);assert.equal(b.jawFlanges[0].parent,b.movingJaw);assert.equal(d.sourceAnimation.available,false);assert.match(d.workingPartsReview.sourceCorrection,/not grounded/);});
test('280 moving jaw circle closure preserves the coupler and short lever lengths',()=>{for(let i=0;i<=512;i++){const s=d.stateAtTime(i/128);near(s.couplerLengthError,0);near(s.rockerLengthError,0);near(s.shortLeverPivot.length(),g.movingJawPivotRadius);}});
test('280 clamped shoe and jaw move at the wheel angular velocity while return is unloaded',()=>{let previous=0;for(let i=0;i<=512;i++){const s=d.stateAtTime(i/128);const slipping=s.stage==='downstroke-clamp-released-wheel-held'&&s.cycleTime<d.timeline.topDwellEnd+.31;assert.ok(s.wheelAngle>=previous-(slipping?.01:1e-12));previous=s.wheelAngle;if(slipping)continue;if(s.driving){near(s.relativeLeverAngle,0);near(s.shoeGap,0);near(s.wheelAngularSpeed,s.jawAngularSpeed);const expected=new T.Vector3(-s.shoeCenter.y,s.shoeCenter.x,0).multiplyScalar(s.wheelAngularSpeed);assert.ok(s.shoeVelocity.distanceTo(expected)<1e-8);}else near(s.wheelAngularSpeed,0);if(s.stage==='bottom-handle-dwell-wheel-held')assert.ok(s.shoeGap>.01);}});
test('280 inferred stroke endpoint advances half a tooth with continuous unwrapped output over many cycles',()=>{near(d.stateAtTime(4).wheelAngle,g.outputStopPitch);near(d.stateAtTime(288).wheelAngle,2*Math.PI);for(let k=-3;k<=73;k++){const a=d.stateAtTime(4*k-1e-7),c=d.stateAtTime(4*k+1e-7);near(a.wheelAngle,c.wheelAngle,1e-9);near(a.jawAngle,c.jawAngle,1e-9);}});
test('280 finite shoe orientation gives inward wedging under the driving tangential reaction',()=>{const p=g.shoeContactPoint,P=g.movingJawPivotRadius,R=g.wheelRadius,n=new T.Vector3(P+p.x,p.y,0).normalize(),opposingTangent=new T.Vector3(n.y,-n.x,0),torque=p.x*opposingTangent.y-p.y*opposingTangent.x,radialDerivative=n.dot(new T.Vector3(-p.y,p.x,0));assert.ok(torque>0&&radialDerivative<0);near(Math.hypot(P+p.x,p.y),R);});
test('280 renderer binds moving pins and bored coupler to the solved travelling jaw',()=>{for(let i=0;i<=64;i++){const t=i/16,s=d.stateAtTime(t);model.update(t);model.root.updateMatrixWorld(true);const lo=b.lowerLinkPin.getWorldPosition(new T.Vector3());near(lo.x,s.lowerPin.x);near(lo.y,s.lowerPin.y);const start=b.finiteCoupler.localToWorld(new T.Vector3()),end=b.finiteCoupler.localToWorld(new T.Vector3(g.couplerLength,0,0));near(start.x,s.upperPin.x);near(start.y,s.upperPin.y);near(end.x,s.lowerPin.x);near(end.y,s.lowerPin.y);near(b.wheelRotor.rotation.z,s.wheelAngle);}});
test('280 finite/load qualification is explicit and readable playback is requested',()=>{assert.equal(d.minimumDisplayCycleSeconds,8);assert.equal(d.hideGround,true);assert.match(d.workingPartsReview.qualification,/backstop.*prescribed/);assert.match(d.workingPartsReview.qualification,/unqualified/);});
test('280 p92: the short arm and the jaw cheeks end in round ends concentric with their pins',()=>{
 const pinR=b.upperLinkPin.geometry.parameters.radiusTop,pin=b.upperLinkPin.position,arm=b.inputCrankArm.geometry.attributes.position,eye=b.inputCrankArm.userData.eyeRadius;
 assert.equal(b.inputCrankArm.parent,b.upperLinkPin.parent);assert.ok(eye>1.3*pinR,`eye ${eye} vs pin ${pinR}`);
 let beyond=0;for(let i=0;i<arm.count;i++){const x=arm.getX(i),y=arm.getY(i),r=Math.hypot(x-pin.x,y-pin.y);assert.ok(r>=eye-1e-3||Math.hypot(x,y)<0.24,`arm vertex inside the eye margin: ${r}`);if(x>=pin.x){beyond++;near(r,eye,1e-3);}}
 assert.ok(beyond>8);
 const P=g.movingJawPivotRadius;for(const cheek of b.jawCheeks){const p=cheek.geometry.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);if(x>P+1e-9){const r=Math.hypot(x-P,y);assert.ok(Math.abs(r-.29)<2e-3||Math.abs(r-.174)<2e-3,`cheek vertex ${r}`);}}}
});
