import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import{createAuthoredOscillatingDrumRatchetMovement as a}from '../src/simulation/authored-oscillating-drum-ratchets.js';
import{createAuthoredAxialPinClutchMovement as b}from '../src/simulation/authored-axial-pin-clutches.js';
import{createAuthoredDicksonReversibleDriveMovement as c}from '../src/simulation/authored-dickson-reversible-drives.js';
import {drumContact as p,drumContactState} from '../src/simulation/oscillating-drum-contact.js';
import {solidSurface,surfacePoints} from './helpers/solid-surface.mjs';
const models=[a({id:360}),b({id:361}),c({id:415})],cache=new Map();
const get=o=>{if(!cache.has(o))cache.set(o,{p:surfacePoints(o.geometry),s:solidSurface(o.geometry)});return cache.get(o);};
function clearance(a,b){let min=Infinity;for(const[x,y]of[[a,b],[b,a]]){const tr=y.matrixWorld.clone().invert().multiply(x.matrixWorld),s=get(y).s;for(const p of get(x).p){const q=p.clone().applyMatrix4(tr);if(s.box.distanceToPoint(q)>.003)continue;min=Math.min(min,s.signedDistance(q,.15));}}return min;}
function sweep(m,pairs,steps=128,tolerance=2e-6){for(let i=0;i<=steps;i++){m.update(12*i/steps);m.root.updateMatrixWorld(true);for(const[a,b]of pairs)assert.ok(clearance(a,b)>-tolerance,`${i}: ${a.userData.role}/${b.userData.role}`);}}
const role=(root,name)=>{let found;root.traverse(o=>{if(o.userData.role===name)found=o;});return found;};

test('360 finite pawl and ratchet remain clear throughout capture, drive and overrun',()=>{const m=models[0],b=m.root.userData.blocks;sweep(m,[[b.pawlTip,b.ratchetWheel],[b.pawlArm,b.ratchetWheel],[b.pawlArm,b.drumBody],[b.pawlArm,role(m.root,'loose-drum-cord-groove')]],256);let count=0;for(let i=0;i<=128;i++){const t=6*i/128,s=m.root.userData.stateAtTime(t);if(!s.ratchetLocked)continue;m.update(t-(m.root.userData.timeline.displayTimeOffset??0));m.root.updateMatrixWorld(true);assert.ok(clearance(b.pawlTip,b.ratchetWheel)<2e-6);assert.ok(Math.abs(s.flywheelAngularSpeed-s.drumAngularSpeed)<1e-10);count++;}assert.ok(count>30);});
test('360 one-way law advances six teeth per beam oscillation without angular teleport',()=>{for(let i=-5;i<=32;i++){const a=drumContactState(6*i),b=drumContactState(6*(i+1));assert.ok(Math.abs(b.angle-a.angle-p.advance)<1e-11);for(const t of[6*i,6*i+p.catchTime,6*i+p.releaseTime])assert.ok(Math.abs(drumContactState(t+1e-8).angle-drumContactState(t-1e-8).angle)<3e-8);}assert.ok(Math.abs(drumContactState(48).angle-drumContactState(0).angle-6*Math.PI)<1e-10);assert.equal(models[0].root.userData.timeline.markedClosurePeriod,48);});
test('361 perpendicular pins have actual side contact at the finite phase lead',()=>{const m=models[1],d=m.root.userData,b=d.blocks,phase=d.dogGeometry.pinContactPhase;sweep(m,[[b.pulleyDog,b.shaftDog],[b.lowerPulley.sheave,b.outputShaft],[b.lowerPulley.hub,b.outputShaft],...b.lowerPulley.flanges.map(o=>[o,b.outputShaft])]);for(const t of[4.5,5,6,7.5]){m.update(t);m.root.updateMatrixWorld(true);const contact=b.outputRotor.localToWorld(new T.Vector3(-.45,.36*Math.cos(phase),-.06));for(const pin of[b.pulleyDog,b.shaftDog])assert.ok(get(pin).s.distance(pin.worldToLocal(contact.clone()))<2e-7,'actual side-contact witness');}});
test('361 real sheave grooves clear the finite belt cross-section through each wrap',()=>{const m=models[1],b=m.root.userData.blocks;for(const t of[0,3.75,4.5,6,8.25]){m.update(t);m.root.updateMatrixWorld(true);for(const [pulley,parent]of[[b.upperPulley,b.driverRotor],[b.lowerPulley,b.slidingPulley]])for(let i=0;i<32;i++)for(let j=0;j<16;j++){const a=i*2*Math.PI/32,c=j*2*Math.PI/16,r=.46+.038*Math.sin(c),world=parent.localToWorld(new T.Vector3(.038*Math.cos(c),r*Math.cos(a),r*Math.sin(a)));assert.ok(!get(pulley.sheave).s.inside(pulley.sheave.worldToLocal(world)));}}});
test('361 fixed bearing passages clear both rotating shafts',()=>{const m=models[1],b=m.root.userData.blocks;sweep(m,b.bearingBlocks.map(o=>[o,o.position.y>0?b.driverShaft:b.outputShaft]),32);});
test('415 both finite pawl faces fit the smooth rim over selection and both drive directions',()=>{const m=models[2],b=m.root.userData.blocks;sweep(m,[[b.bPawl.children[0],b.wheelRing],[b.cPawl.children[0],b.wheelRing]],128,1.7e-5);for(const[t,pawl]of[[1.5,b.cPawl],[9.5,b.bPawl]]){m.update(t-m.root.userData.geometry.sourceTime);m.root.updateMatrixWorld(true);assert.ok(Math.abs(clearance(pawl.children[0],b.wheelRing))<4e-5,'actual finite engagement');}});
test('415 actual hub, web, spokes and hinge bores clear their independent shafts',()=>{const m=models[2],b=m.root.userData.blocks,parts=[];for(const name of['fixed-rear-bearing','wheel-D-hub-fast-with-smooth-rim','lever-A-loose-hub-on-wheel-D-shaft','T-shaped-rigid-body-of-lever-A','translucent-wheel-D-web'])parts.push([role(m.root,name),b.fixedShaft]);for(const o of b.wheelRotor.children)if(o.userData.role==='wheel-D-spoke-fast-with-rim-and-hub')parts.push([o,b.fixedShaft]);for(const[name,pawl]of[['B',b.bPawl],['C',b.cPawl]])for(const part of[pawl.children[0],pawl.children[1]])parts.push([part,role(m.root,`fixed-lever-pin-for-pawl-${name}`)]);sweep(m,parts,32);});
test('all three use retained geometry and explicit prescribed-load qualifications',()=>{for(const m of models){const before=[];m.root.traverse(o=>before.push([o,o.geometry]));for(let i=0;i<32;i++)m.update(i/3);const after=[];m.root.traverse(o=>after.push([o,o.geometry]));assert.deepEqual(before,after);assert.equal(m.root.userData.hideGround,true);assert.equal(m.root.userData.minimumDisplayCycleSeconds,12);assert.match(m.root.userData.workingPartsReview.qualification,/not simulated|unqualified|prescribed/);assert.match(m.root.userData.reconstructionNote,/not simulated/);}});

test('360 public state follows actual capture and coast without legacy impulse labels',()=>{const m=models[0],d=m.root.userData,off=d.timeline.displayTimeOffset??0;for(const t of[0,p.catchTime,p.catchTime+.1,p.releaseTime+.1,6.4,18.5]){m.update(t-off);const s=d.currentState,q=drumContactState(t);assert.deepEqual(s,d.stateAtTime(t));assert.equal(s.ratchetLocked,q.locked);assert.equal(s.carrierCatching,q.locked);assert.equal(s.flywheelAngularSpeed,q.speed);assert.equal(d.blocks.flywheelRotor.rotation.z,q.angle);assert.ok(s.relativeToothPhase>=0&&s.relativeToothPhase<1);if(q.locked)assert.ok(Math.min(s.relativeToothPhase,1-s.relativeToothPhase)<1e-12);}assert.equal(d.degreesOfFreedom.storedEnergyStates,0);assert.equal(d.dynamics.flywheelAngularSpeed,null);});
