import {cordTreadleSource,cordTreadleParameters,cordTreadleState} from '../cord-treadle-motion.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
// A dynamics diagnostic, not a qualified visible assembly or production model.
export function makeCordTreadlePhysics(mujoco,{timestep=.0005,cord=true,period=4,floor=false}={}){
 const g=cordTreadleParameters({...cordTreadleSource,period}),speed=2*Math.PI/period,footLength=g.footLength,armLength=g.armLength,pivot=[...g.pivot,0],guide=[...g.guide,.64],pin=[...g.pin,.64],diskRadius=cordTreadleSource.diskRadius*cordTreadleSource.scale;
 const h=.0001,initialVelocity=(cordTreadleState(h,g).treadleAngle-cordTreadleState(period-h,g).treadleAngle)/(2*h);
 // Uniform unit-mass treadle, with its mass center halfway along the beam.
 // These inertias are provisional until the source-shaped solids are rebuilt.
 const beamWidth=.17,beamDepth=.24,mass=1,ix=(beamWidth**2+beamDepth**2)/12,iy=(footLength**2+beamDepth**2)/12,iz=(footLength**2+beamWidth**2)/12;
 const xml=`<mujoco><compiler angle="radian"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="implicitfast" solver="Newton" iterations="80" tolerance="1e-10"/><default><site size=".01"/><geom contype="0" conaffinity="0"/></default><worldbody>
 ${floor?`<geom name="floor" type="box" pos="3 ${g.groundY-.1} .17" size="10 .1 2" contype="1" conaffinity="2" friction=".8 .01 .001" solref=".002 1" solimp=".999 .9999 .0001"/>`:""}
 <geom name="wrap" type="cylinder" pos="${guide.join(' ')}" size="${g.guideRadius} .1"/><site name="upper" pos="${guide[0]} ${guide[1]+g.guideRadius+.1} ${guide[2]}"/>
 <body name="disk"><joint name="disk" axis="0 0 1"/><inertial pos="0 0 0" mass="1" diaginertia="${diskRadius**2/4} ${diskRadius**2/4} ${diskRadius**2/2}"/><site name="crank-eye" pos="${pin.join(' ')}"/></body>
 <body name="treadle" pos="${pivot.join(' ')}"><joint name="treadle" axis="0 0 1" damping=".02"/><inertial pos="${-footLength/2} 0 ${.17}" mass="${mass}" diaginertia="${ix} ${iy} ${iz}"/>${floor?`<geom name="treadle-beam" type="box" pos="${-footLength/2} 0 .17" size="${footLength/2} ${beamWidth/2} ${beamDepth/2}" contype="2" conaffinity="1" friction=".8 .01 .001" solref=".002 1" solimp=".999 .9999 .0001"/>`:""}<site name="treadle-eye" pos="${-armLength} 0 ${.64}"/></body>
 </worldbody>${cord?`<tendon><spatial name="cord" limited="true" range="0 ${g.cordLength}" solreflimit=".002 1" solimplimit=".999 .9999 .0001"><site site="crank-eye"/><geom geom="wrap" sidesite="upper"/><site site="treadle-eye"/></spatial></tendon>`:''}
 <actuator><position joint="disk" kp="10000" kv="100"/></actuator></mujoco>`;
 const p=createMujocoSimulation(mujoco,{xml,initialize:({data})=>{data.qpos.set([0,g.initialTreadle]);data.qvel.set([speed,initialVelocity]);},beforeStep:({data,time})=>{data.ctrl[0]=speed*(time+.01);}});
 return Object.assign(p,{description:{movement:159,period,timestep,cord,floor,groundY:g.groundY,footLength,armLength,pivot,guide,pin,cordLength:g.cordLength,guideRadius:g.guideRadius,initialTreadle:g.initialTreadle,mass,assumptions:'Diagnostic only. Legacy source-center geometry, uniform unit-mass treadle, driven disk, passive treadle under gravity, frictionless massless cord with unilateral length limit around a fixed cylinder. Pulley inertia, human foot force, remaining visible-support contact and final assembly inertias are unqualified. Optional floor contact uses a box matching the provisional treadle dimensions.'},state:()=>({time:p.data.time,footBottom:g.pivot[1]+Math.min(0,-footLength*Math.sin(p.data.qpos[1]))-beamWidth/2*Math.abs(Math.cos(p.data.qpos[1])),floorContacts:floor?p.data.ncon:0,qpos:Array.from(p.data.qpos),qvel:Array.from(p.data.qvel),cordLength:cord?p.data.ten_length[0]:null,passiveConstraintTorque:p.data.qfrc_constraint[1],actuatorTorque:p.data.qfrc_actuator[1]})});
}
