import {cordTreadleSource,cordTreadleParameters,cordTreadleState} from '../cord-treadle-motion.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
// Experimental planar, freely hinged finite rope. Not a production assembly.
export function makeFiniteCordTreadlePhysics(mujoco,{segments=96,timestep=.0001,period=4,ropeMass=.08,ropeRadius=.045,friction=.5}={}){
 if(!Number.isInteger(segments)||segments<16)throw new RangeError('At least 16 rope segments required');
 const g=cordTreadleParameters({...cordTreadleSource,period}),speed=2*Math.PI/period,z=.64,L=g.footLength;
 const path=time=>{const s=cordTreadleState(time,g),arc=-g.guideRadius*s.sweep;return Array.from({length:segments+1},(_,i)=>{const d=s.length*i/segments;if(d<=s.incoming){const f=d/s.incoming;return s.pin.map((v,j)=>v+(s.entry[j]-v)*f);}if(d<s.incoming+arc){const a=s.entryAngle-(d-s.incoming)/g.guideRadius;return[g.guide[0]+g.guideRadius*Math.cos(a),g.guide[1]+g.guideRadius*Math.sin(a)];}const f=(d-s.incoming-arc)/s.outgoing;return s.exit.map((v,j)=>v+(s.eye[j]-v)*f);});};
 const points=path(0),lengths=points.slice(1).map((p,i)=>Math.hypot(p[0]-points[i][0],p[1]-points[i][1])),angles=points.slice(1).map((p,i)=>Math.atan2(p[1]-points[i][1],p[0]-points[i][0]));
 if(Math.min(...lengths)<2.05*ropeRadius)throw new RangeError('Rope links too short for nonadjacent self contact');
 const totalLength=lengths.reduce((a,b)=>a+b,0),h=.0001,before=path(period-h),after=path(h);
 const angularVelocities=lengths.map((_,i)=>wrap(Math.atan2(after[i+1][1]-after[i][1],after[i+1][0]-after[i][0])-Math.atan2(before[i+1][1]-before[i][1],before[i+1][0]-before[i][0]))/(2*h));
 const collision='condim="3" friction="'+friction+' .001 .001" solref=".002 1" solimp=".999 .9999 .0001"';
 const rope=lengths.map((length,i)=>{const mass=ropeMass*length/totalLength,axial=mass*ropeRadius**2/2,transverse=mass*(length**2+3*ropeRadius**2)/12;return `<body name="rope${i}" pos="${i?`${lengths[i-1]} 0 0`:`${points[0].join(' ')} ${z}`}" euler="0 0 ${i?wrap(angles[i]-angles[i-1]):angles[i]}"><joint name="rope${i}" axis="0 0 1" damping=".000001" armature="1e-9"/><inertial pos="${length/2} 0 0" mass="${mass}" diaginertia="${axial} ${transverse} ${transverse}"/><geom name="rope${i}" type="capsule" fromto="0 0 0 ${length} 0 0" size="${ropeRadius}" contype="1" conaffinity="7" ${collision}/>${i===segments-1?`<site name="rope-end" pos="${length} 0 0"/>`:''}`;}).join('')+'</body>'.repeat(segments);
 const r=cordTreadleSource.diskRadius*cordTreadleSource.scale,pulleyRadius=g.guideRadius-ropeRadius;
 const xml=`<mujoco><compiler angle="radian"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="implicitfast" solver="Newton" iterations="80" tolerance="1e-9" cone="elliptic"/><size memory="64M"/><default><site size=".01"/><geom contype="0" conaffinity="0"/></default><worldbody>
 <geom name="floor" type="box" pos="3 ${g.groundY-.1} .17" size="10 .1 2" contype="4" conaffinity="9" ${collision}/>
 <body name="disk"><joint name="disk" axis="0 0 1"/><inertial pos="0 0 0" mass="1" diaginertia="${r*r/4} ${r*r/4} ${r*r/2}"/>${rope}</body>
 <body name="pulley" pos="${g.guide.join(' ')} ${z}"><joint name="pulley" axis="0 0 1" damping=".0001"/><inertial pos="0 0 0" mass=".05" diaginertia="${.05*pulleyRadius**2/4} ${.05*pulleyRadius**2/4} ${.05*pulleyRadius**2/2}"/><geom name="pulley" type="cylinder" size="${pulleyRadius} .1" contype="2" conaffinity="1" ${collision}/></body>
 <body name="treadle" pos="${g.pivot.join(' ')} 0"><joint name="treadle" axis="0 0 1" damping=".02"/><inertial pos="${-L/2} 0 .17" mass="1" diaginertia="${(.17**2+.24**2)/12} ${(L*L+.24**2)/12} ${(L*L+.17**2)/12}"/><geom name="treadle" type="box" pos="${-L/2} 0 .17" size="${L/2} .085 .12" contype="8" conaffinity="4" ${collision}/><site name="treadle-eye" pos="${-g.armLength} 0 ${z}"/></body>
 </worldbody><equality><connect site1="rope-end" site2="treadle-eye" solref=".002 1" solimp=".99999 .99999 .0001"/></equality><actuator><position joint="disk" kp="10000" kv="100"/></actuator></mujoco>`;
 const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{const set=(name,q,v)=>{const j=id('mjOBJ_JOINT',name);data.qpos[model.jnt_qposadr[j]]=q;data.qvel[model.jnt_dofadr[j]]=v;};set('disk',0,speed);set('treadle',g.initialTreadle,(cordTreadleState(h,g).treadleAngle-cordTreadleState(period-h,g).treadleAngle)/(2*h));for(let i=0;i<segments;i++)set('rope'+i,0,angularVelocities[i]-(i?angularVelocities[i-1]:speed));},beforeStep:({data,time})=>{data.ctrl[0]=speed*(time+.01);}});
 const coordinate=name=>p.model.jnt_qposadr[p.id('mjOBJ_JOINT',name)],disk=coordinate('disk'),treadle=coordinate('treadle'),pulley=coordinate('pulley'),bodyIds=lengths.map((_,i)=>p.id('mjOBJ_BODY','rope'+i)),end=p.id('mjOBJ_SITE','rope-end'),eye=p.id('mjOBJ_SITE','treadle-eye');
 return Object.assign(p,{description:{segments,timestep,period,ropeMass,ropeRadius,friction,totalLength,nominalLength:g.cordLength,groundY:g.groundY,pulleyRadius,assumptions:'Experimental planar articulated rope with finite capsule self-contact, gravity, passive pulley friction and floor contact. Uniform beam and provisional rope/pulley masses; driven disk only. Attachment compliance and resolution remain unqualified.'},state:()=>{const q=p.data.qpos[treadle],tip=Array.from(p.data.site_xpos.slice(end*3,end*3+3)),attachment=Array.from(p.data.site_xpos.slice(eye*3,eye*3+3));return{time:p.data.time,disk:p.data.qpos[disk],treadle:q,pulley:p.data.qpos[pulley],contacts:p.data.ncon,attachmentError:Math.hypot(...tip.map((v,i)=>v-attachment[i])),footClearance:g.pivot[1]+Math.min(0,-L*Math.sin(q))-.085*Math.abs(Math.cos(q))-g.groundY,points:[...bodyIds.map(id=>Array.from(p.data.xpos.slice(id*3,id*3+3))),tip]};}});
}
