import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
import {segmentClampStroke} from './profile.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');
export function makeSegmentClampPhysics(mujoco,visual,{timestep=.001,period=5,amplitude=segmentClampStroke,torque=8,contactTime=.002,friction=0,gravity=-9.81,load=0,jawContact=true}={}){
 if(![timestep,period,amplitude,torque,contactTime].every(v=>Number.isFinite(v)&&v>0)||!Number.isFinite(friction)||friction<0||![gravity,load].every(Number.isFinite))throw new RangeError('Invalid 120 physics options');
 const u=visual.root.userData,f=u.profile,names=['input','external','internal'],mass=Object.fromEntries(names.map(n=>[n,rigidFamilyInertia(u.parts,u.families,n)])),density=1/mass.internal.volume,assets=[];
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const groups={},geoms=(name,mask,other)=>u.cells[name].map((cell,i)=>{const id=name+i;groups[id]=name;assets.push(`<mesh name="${id}" vertex="${vec(cell.flat())}"/>`);return `<geom name="${id}" type="mesh" mesh="${id}" contype="${mask}" conaffinity="${other}"/>`;}).join('');
 const small=geoms('smallPinion',1,2),large=geoms('largePinion',4,8),external=geoms('externalTeeth',2,1),internal=geoms('internalTeeth',8,4),left=geoms('leftJaw',jawContact?16:0,jawContact?32:0),right=geoms('rightJaw',jawContact?32:0,jawContact?16:0);
 const xml=`<mujoco model="120 compound-pinion segment clamp"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 ${gravity} 0" integrator="discrete" solver="Newton" iterations="80" tolerance="1e-10" cone="elliptic"><flag multiccd="disable" diagexact="enable"/></option><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp=".99 .999 .001"/></default><asset>${assets.join('')}</asset><worldbody><body name="input" pos="${vec([...f.input,0])}"><joint name="input" damping=".001"/>${inertia('input')}${small}${large}</body><body name="external"><joint name="external" damping=".001"/>${inertia('external')}${external}${left}</body><body name="internal"><joint name="internal" damping=".001"/>${inertia('internal')}${internal}${right}</body></worldbody><actuator><position joint="input" kp="400" kv="8" forcerange="${-torque} ${torque}"/></actuator></mujoco>`;
 const omega=2*Math.PI/period,input=time=>({position:amplitude*(1-Math.cos(omega*time))/2,velocity:amplitude*omega*Math.sin(omega*time)/2});
 const p=createMujocoSimulation(mujoco,{xml,beforeStep:({data,time})=>{const s=input(time);data.ctrl[0]=s.position+.02*s.velocity;data.qfrc_applied[1]=load;data.qfrc_applied[2]=-load;}});
 return Object.assign(p,{bodies:Object.fromEntries(names.map(n=>[n,p.id('mjOBJ_BODY',n)])),geomGroups:Object.fromEntries(Object.entries(groups).map(([id,name])=>[p.id('mjOBJ_GEOM',id),name])),description:{xml,mass,density,input,options:{timestep,period,amplitude,torque,contactTime,friction,gravity,load,jawContact},assumptions:'One torque-limited reversing shaft drives both passive jaws through native internal and external gear contact. The default stroke closes the jaws part-way with both segments centred on their pinions; a longer stroke is stopped by native jaw contact. Shaft bearings are ideal; reversing input, recessed frame arms, hidden depths and widened jaws are reconstructed. Collision boundaries approximate the visible working surfaces within 0.05 source pixel by default. Mass and forces use an uncalibrated normalized scale.'}});
}
