import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');
export function makeRollerYokePhysics(mujoco,visual,{timestep=.0005,period=5,startup=.2,friction=.3,contactTime=.002,rollerDamping=1e-7}={}){
 if(![timestep,period,startup,contactTime].every(v=>Number.isFinite(v)&&v>0)||![friction,rollerDamping].every(v=>Number.isFinite(v)&&v>=0))throw new RangeError('Invalid 117 physics options');
 const u=visual.root.userData,names=['input','yoke','upper','lower'],mass=Object.fromEntries(names.map(n=>[n,rigidFamilyInertia(u.parts,u.families,n)])),density=1/mass.yoke.volume,assets=[],geoms=[];
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const c=u.collision;for(const [i,cell]of c.cells.entries()){const name='cam'+i;assets.push(`<mesh name="${name}" vertex="${vec([c.low,c.high].flatMap(z=>cell.flatMap(p=>[...p,z])))}"/>`);geoms.push(`<geom name="${name}" type="mesh" mesh="${name}" contype="1" conaffinity="2"/>`);}
 const rollers=['upper','lower'].map((n,i)=>`<body name="${n}" pos="0 ${(i?-1:1)*u.source.meanPitchRadius} 0"><joint name="${n}" axis="0 0 1" damping="${rollerDamping}"/>${inertia(n)}<geom name="${n}" type="capsule" size="${u.source.rollerRadius}" fromto="0 0 -.002 0 0 .002" contype="2" conaffinity="1"/></body>`).join('');
 const xml=`<mujoco model="117 cam and roller yoke"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="discrete" solver="Newton" iterations="80" tolerance="1e-10" cone="elliptic"><flag multiccd="disable" diagexact="enable"/></option><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp=".99 .999 .001"/></default><asset>${assets.join('')}</asset><worldbody><body name="input"><joint name="input" axis="0 0 1" damping=".01"/>${inertia('input')}${geoms.join('')}</body><body name="yoke"><joint name="yoke" type="slide" axis="0 1 0" damping=".02"/>${inertia('yoke')}${rollers}</body></worldbody><actuator><position name="motor" joint="input" kp="10000" kv="200"/></actuator></mujoco>`;
 const omega=-2*Math.PI/period,input=time=>{const e=Math.exp(-time/startup);return{angle:omega*(time-startup*(1-e)),velocity:omega*(1-e)};};
 const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{data.qpos[model.jnt_qposadr[id('mjOBJ_JOINT','yoke')]]=u.profile.initialQ;},beforeStep:({data,time})=>{const s=input(time);data.ctrl[0]=s.angle+.02*s.velocity;}});
 return Object.assign(p,{joints:Object.fromEntries(names.map(n=>{const id=p.id('mjOBJ_JOINT',n);return[n,{q:p.model.jnt_qposadr[id],v:p.model.jnt_dofadr[id]}];})),bodies:Object.fromEntries(names.map(n=>[n,p.id('mjOBJ_BODY',n)])),description:{xml,mass,density,input,options:{timestep,period,startup,friction,contactTime,rollerDamping},assumptions:'Only the cam is driven. The two roller hinges and yoke slide are passive. Ideal bearings and a vertical guide retain the source topology. Circular capsule working surfaces approximate the finite roller rims; their inaccessible pin bores are filled for collision only. Hidden depth and the lower stem extension beyond the engraving break are inferred.'}});
}
