import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');
export function makeStrokeDoublerPhysics(mujoco,visual,{timestep=.0005,period=5,contactTime=.002,friction=0,load=0}={}){
 if(![timestep,period,contactTime].every(v=>Number.isFinite(v)&&v>0)||!Number.isFinite(friction)||friction<0||!Number.isFinite(load))throw new RangeError('Invalid 118 physics options');
 const u=visual.root.userData,names=['carrier','pinion','rack'],mass=Object.fromEntries(names.map(n=>[n,rigidFamilyInertia(u.parts,u.families,n)])),density=1/mass.rack.volume,assets=[];
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const geoms=(name,mask,other)=>u.cells[name].map((cell,i)=>{const id=name+i;assets.push(`<mesh name="${id}" vertex="${vec(cell.flat())}"/>`);return `<geom name="${id}" type="mesh" mesh="${id}" contype="${mask}" conaffinity="${other}"/>`;}).join('');
 const pinion=geoms('pinion',1,2),upper=geoms('upperRack',2,1),lower=geoms('lowerRack',2,1);
 const xml=`<mujoco model="118 stroke-doubling pinion"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="discrete" solver="Newton" iterations="80" tolerance="1e-10" cone="elliptic"><flag multiccd="disable" diagexact="enable"/></option><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp=".99 .999 .001"/></default><asset>${assets.join('')}</asset><worldbody>${lower}<body name="carrier"><joint name="carrier" type="slide" axis="1 0 0" damping=".01"/>${inertia('carrier')}<body name="pinion"><joint name="pinion" axis="0 0 1" damping=".0001"/>${inertia('pinion')}${pinion}</body></body><body name="rack"><joint name="rack" type="slide" axis="1 0 0" damping=".01"/>${inertia('rack')}${upper}</body></worldbody><actuator><position name="input" joint="carrier" kp="10000" kv="200"/></actuator></mujoco>`;
 const omega=2*Math.PI/period,input=time=>{const e=Math.exp(-((time/.25)**2)),ramp=1-e,first=2*time/.25**2*e;return{position:u.profile.amplitude*Math.sin(omega*time)*ramp,velocity:u.profile.amplitude*(omega*Math.cos(omega*time)*ramp+Math.sin(omega*time)*first)};};
 const p=createMujocoSimulation(mujoco,{xml,initialize:({data})=>{data.qfrc_applied[2]=load;},beforeStep:({data,time})=>{const s=input(time);data.ctrl[0]=s.position+.02*s.velocity;}});
 return Object.assign(p,{joints:Object.fromEntries(names.map(n=>{const id=p.id('mjOBJ_JOINT',n);return[n,{q:p.model.jnt_qposadr[id],v:p.model.jnt_dofadr[id]}];})),bodies:Object.fromEntries(names.map(n=>[n,p.id('mjOBJ_BODY',n)])),description:{xml,mass,density,input,options:{timestep,period,contactTime,friction,load},assumptions:'Only the pitman-carried spindle is actuated. Native tooth contact determines pinion rotation and the upper rack stroke. Bearings and translation guides are ideal. Hidden depth, input stroke and timing, and the three static support webs are inferred.'}});
}
