import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');

export function makeVariableTraversePhysics(mujoco,visual,{timestep=.001,period=4,contactTime=.002,friction=0,load=0}={}){
 if(![timestep,period,contactTime].every(v=>Number.isFinite(v)&&v>0)||!Number.isFinite(friction)||friction<0||!Number.isFinite(load))throw new RangeError('Invalid 122 physics options');
 const u=visual.root.userData,f=u.profile,names=Object.keys(f.position),mass=Object.fromEntries(names.map(n=>[n,rigidFamilyInertia(u.parts,u.families,n)])),density=1/mass.lower.volume,assets=[],groups={};
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const geoms=(name,mask,other)=>u.cells[name].map((cell,i)=>{const id=name+i;groups[id]=name;assets.push(`<mesh name="${id}" vertex="${vec(cell.flat())}"/>`);return `<geom name="${id}" type="mesh" mesh="${id}" contype="${mask}" conaffinity="${other}"/>`;}).join('');
 const upper=geoms('upperGear',1,2),lower=geoms('lowerGear',2,1);
 const gearBody=(n,geoms)=>`<body name="${n}" pos="${vec([...f.centers[n],0])}"><joint name="${n}" damping=".001"/>${inertia(n)}${geoms}<body name="${n}Rod" pos="${vec([...f[n+'Crank'],0])}"><joint name="${n}Rod" damping=".001"/>${inertia(n+'Rod')}<site name="${n}RodEnd" pos="${vec([...f[n+'RodEnd'],.32])}"/></body></body>`;
 const xml=`<mujoco model="122 variable geared traverse"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="discrete" solver="Newton" iterations="80" tolerance="1e-10" cone="elliptic"><flag multiccd="disable" diagexact="enable"/></option><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp=".99 .999 .001"/><equality solref=".002 1" solimp=".999 .9999 .0001"/></default><asset>${assets.join('')}</asset><worldbody>${gearBody('upper',upper)}${gearBody('lower',lower)}<body name="slider" pos="${vec([...f.position.slider,0])}"><joint name="slider" type="slide" axis="${vec([...f.slideDirection,0])}" damping=".01"/>${inertia('slider')}<body name="floating"><joint name="floating" damping=".001"/>${inertia('floating')}<site name="topPin" pos="${vec([...f.topPin,.32])}"/><site name="bottomPin" pos="${vec([...f.bottomPin,.32])}"/></body></body></worldbody><equality><connect site1="upperRodEnd" site2="topPin"/><connect site1="lowerRodEnd" site2="bottomPin"/></equality><actuator><position name="input" joint="lower" kp="10000" kv="200"/></actuator></mujoco>`;
 const omega=2*Math.PI/period,input=time=>({position:omega*(time-.25*(1-Math.exp(-time/.25))),velocity:omega*(1-Math.exp(-time/.25))});
 const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{data.qfrc_applied[model.jnt_dofadr[id('mjOBJ_JOINT','slider')]]=load;},beforeStep:({data,time})=>{const q=input(time);data.ctrl[0]=q.position+.02*q.velocity;}});
 const joints=Object.fromEntries(names.map(n=>{const id=p.id('mjOBJ_JOINT',n);return[n,{q:p.model.jnt_qposadr[id],v:p.model.jnt_dofadr[id]}];}));
 return Object.assign(p,{joints,bodies:Object.fromEntries(names.map(n=>[n,p.id('mjOBJ_BODY',n)])),geomGroups:Object.fromEntries(Object.entries(groups).map(([id,name])=>[p.id('mjOBJ_GEOM',id),name])),description:{xml,mass,density,input,options:{timestep,period,contactTime,friction,load},assumptions:'Only the lower gear is actuated. Native involute contact drives the upper gear; ideal rod pins close the two loops into a passive guided output bar. The guide follows the drawn bar axis. Bearing constraints, axial depths, uniform density and drive timing are inferred. Crank radii are reduced by 15 percent to preserve the source assembly branch through the complete repeating pattern. No upper-gear angle, rod angle or bar travel is prescribed.'}});
}
