import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');
export function makeEqualRacksPhysics(mujoco,visual,{timestep=.001,period=6,contactTime=.004,friction=0,load=0,impedance=.99,integrator='discrete',exactInertia=true,drive='paired'}={}){
 if(![timestep,period,contactTime].every(x=>Number.isFinite(x)&&x>0)||!Number.isFinite(friction)||friction<0||!Number.isFinite(load)||!Number.isFinite(impedance)||impedance<=0||impedance>=1||!['discrete','implicitfast','implicit','Euler'].includes(integrator)||typeof exactInertia!=='boolean'||!['paired','upper'].includes(drive))throw new RangeError('Invalid 115 physics options');
 const u=visual.root.userData,f=u.profile,names=['upper','lower','frame'],mass=Object.fromEntries(names.map(n=>[n,rigidFamilyInertia(u.parts,u.families,n)])),density=1/mass.frame.volume,assets=[];
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const geoms=(n,mask,other)=>u.cells[n].map((cell,i)=>{const id=n+i;assets.push(`<mesh name="${id}" vertex="${vec(cell.flat())}"/>`);return `<geom name="${id}" type="mesh" mesh="${id}" contype="${mask}" conaffinity="${other}"/>`;}).join('');
 const upper=geoms('upper',1,6),lower=geoms('lower',2,5),frame=geoms('frame',4,3);
 const transmission=drive==='paired'?'<tendon><fixed name="shaft_drive"><joint joint="upper" coef="-.5"/><joint joint="lower" coef=".5"/></fixed></tendon><actuator><position tendon="shaft_drive" kp="1200" kv="30"/></actuator>':'<actuator><position joint="upper" kp="1200" kv="30"/></actuator>';
 const xml=`<mujoco model="115 equal pinions and double rack"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="${integrator}" solver="Newton" cone="elliptic" iterations="60" tolerance="1e-10"><flag diagexact="${exactInertia?'enable':'disable'}"/></option><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp="${impedance} ${1-(1-impedance)/10} .001"/></default><asset>${assets.join('')}</asset><worldbody><body name="upper" pos="0 ${f.workingRadius} 0"><joint name="upper" axis="0 0 1" damping=".001"/>${inertia('upper')}${upper}</body><body name="lower" pos="0 ${-f.workingRadius} 0"><joint name="lower" axis="0 0 1" damping=".001"/>${inertia('lower')}${lower}</body><body name="frame"><joint name="frame" type="slide" axis="1 0 0" damping=".02"/>${inertia('frame')}${frame}</body></worldbody>${transmission}</mujoco>`;
 const omega=2*Math.PI/period,input=t=>{const s=Math.exp(-((t/.25)**2)),ramp=1-s,rd=2*t/.25**2*s;return{position:f.amplitude*Math.sin(omega*t)*ramp,velocity:f.amplitude*(omega*Math.cos(omega*t)*ramp+Math.sin(omega*t)*rd)};};
 const physics=createMujocoSimulation(mujoco,{xml,initialize:({data})=>{data.qfrc_applied[2]=load;},beforeStep:({data,time})=>{const s=input(time);data.ctrl[0]=(drive==='paired'?1:-1)*(s.position+.025*s.velocity)/f.pitchRadius;}});
 return Object.assign(physics,{bodies:Object.fromEntries(names.map(n=>[n,physics.id('mjOBJ_BODY',n)])),description:{xml,mass,density,input,options:{timestep,period,contactTime,friction,load,impedance,integrator,exactInertia,drive},assumptions:'The paired input applies equal opposite torques through a fixed tendon transmission to both shafts; upper-only drive is a diagnostic option. The frame moves only through native tooth contact, with no gear equality. Shaft axes and the horizontal guide are ideal. Equal profile-shifted pinions, uniform rack pitch, depth and a reversing demonstration stroke are reconstructed. Equal force is not imposed on the native contacts.'}});
}
