import json,os
import numpy as np
from scipy.ndimage import minimum_filter,maximum_filter
rows=json.load(open('/dev/shm/variable-face-gears.json'));result={}
for row in rows:
 nodes=[];sizes=[]
 for tooth in row['teeth']:
  s=tooth['spec'];x,y=np.meshgrid(np.linspace(-s['length']/2,s['length']/2,s['nx']+1),np.linspace(-s['width']/2,s['width']/2,s['ny']+1),indexing='ij');a=tooth['angle'];nodes.extend(np.stack([tooth['position'][0]+x.flatten()*np.cos(a)-y.flatten()*np.sin(a),tooth['position'][1]+x.flatten()*np.sin(a)+y.flatten()*np.cos(a)],axis=-1));sizes.append(x.shape)
 nodes=np.array(nodes);profile=np.array(row['cutter']['outline']);R=np.linalg.norm(profile,axis=1).max();depth=row['cutter']['depth'];h=np.full(len(nodes),row['teeth'][0]['spec']['tip']);alpha=np.arange(len(nodes))
 for angle,pinion,center,z in row['poses']:
  x=nodes[:,0]*np.cos(angle)-nodes[:,1]*np.sin(angle);y=nodes[:,0]*np.sin(angle)+nodes[:,1]*np.cos(angle)
  axial=x-center if row['id']==219 else y-center;transverse=y if row['id']==219 else x
  mask=(np.abs(axial)<=depth/2+1e-9)&(np.abs(transverse)<R);ids=alpha[mask]
  if not len(ids):continue
  scale=np.ones(len(ids)) if row['id']==219 else .68+.32*(axial[mask]/depth+.5)
  if row['id']==219:xp=profile[:,0]*np.sin(pinion)+profile[:,1]*np.cos(pinion);zp=-profile[:,0]*np.cos(pinion)+profile[:,1]*np.sin(pinion)
  else:xp=profile[:,0]*np.cos(pinion)-profile[:,1]*np.sin(pinion);zp=-profile[:,0]*np.sin(pinion)-profile[:,1]*np.cos(pinion)
  xp2=np.roll(xp,-1);zp2=np.roll(zp,-1);v=transverse[mask]/scale
  crosses=(v[:,None]>=np.minimum(xp,xp2))&(v[:,None]<=np.maximum(xp,xp2))&(np.abs(xp2-xp)>1e-12)
  with np.errstate(divide='ignore',invalid='ignore'):cuts=z+scale[:,None]*(zp+(v[:,None]-xp)/(xp2-xp)*(zp2-zp))
  if row['id']==219:h[ids]=np.minimum(h[ids],np.min(np.where(crosses,cuts,np.inf),axis=1)-.0025)
  else:h[ids]=np.maximum(h[ids],np.max(np.where(crosses,cuts,-np.inf),axis=1)+.0015)
 heights=[];offset=0
 for shape,tooth in zip(sizes,row['teeth']):
  count=np.prod(shape);grid=h[offset:offset+count].reshape(shape);offset+=count
  # Conservative neighboring envelope avoids adding material across concave cutter-tip bridges.
  grid=(minimum_filter if row['id']==219 else maximum_filter)(grid,size=(3,3),mode='nearest')
  if row['id']==219:assert grid.min()>tooth['spec']['base']
  else:assert grid.max()<tooth['spec']['base']
  heights.append(np.round(grid.flatten(),7).tolist())
 result[row['id']]=heights;print({'id':row['id'],'teeth':len(heights),'samples':len(h),'min':float(h.min()),'max':float(h.max())},flush=True)
with open(os.environ.get('BAKED_OUTPUT','src/simulation/generated-variable-face-gears.js'),'w') as f:f.write('// Generated by scripts/generate-variable-face-gears.py.\nexport default '+json.dumps(result,separators=(',',':'))+';\n')
