"""Generate the relief of movement 394's toothed ends (C. Parsons's endless rack).

Pass 99. The straight rows are Brown's box notches: a zero-pressure-angle
rack whose tooth corners, on the pitch line, drive the pinion's involutes of
its pitch circle. The toothed semicircular ends are internal gears of 14
teeth round the same 10-tooth pinion; their zero-angle involute spaces are
exactly conjugate along the line of action, but outside it the pinion tips
sweep the ring tooth corners (a four-tooth difference). As a gear shaper would,
each end's spaces are relieved by the sweep of the pinion itself through the
end and the adjacent row spaces, turned 0.0015 (arc at the pitch circle) each
way for running clearance. The right end is computed; the left end is the
same relief turned half a turn (the path and tooth phase are symmetric).

Usage: node scripts/export-parsons-geometry.mjs /dev/shm/parsons-geometry.json
       python3 scripts/generate-parsons-ends.py /dev/shm/parsons-geometry.json
"""
import json, math, os, sys
from shapely import affinity
from shapely.geometry import Polygon, box
from shapely.ops import unary_union

source = json.load(open(sys.argv[1] if len(sys.argv) > 1 else '/dev/shm/parsons-geometry.json'))
g = source['design']
L, e, rp = g['halfStraight'], g['eccentricity'], g['pinionPitchRadius']
pitch = g['pitch']
CLEARANCE = 0.0015
SAMPLES = 900  # poses over the end's arc
pinion = Polygon(source['pinion'])
arc = math.pi * e

def pose(s, turn):
    # right end and the upper row just before it (parsonsPathPoint)
    if s < 2 * L:
        x, y = -L + s, e
    else:
        a = math.pi / 2 - (s - 2 * L) / e
        if a < -math.pi / 2:
            x, y = L - (s - 2 * L - arc), -e
        else:
            x, y = L + e * math.cos(a), e * math.sin(a)
    return affinity.translate(affinity.rotate(pinion, math.pi / 2 + s / rp + turn, origin=(0, 0), use_radians=True), x, y)

reach = int(SAMPLES * 0.6)
sweep = []
for i in range(-reach, SAMPLES + reach + 1):
    s = 2 * L + arc * i / SAMPLES
    for turn in (CLEARANCE / rp, -CLEARANCE / rp):
        sweep.append(pose(s, turn))
region = box(L - 1.6 * pitch, -3, L + 3, 3)
relief = unary_union(sweep).intersection(region).simplify(1e-4, preserve_topology=True)
if relief.geom_type != 'Polygon':
    raise SystemExit(f'unexpected relief {relief.geom_type}')
ring = [[round(x, 6), round(y, 6)] for x, y in relief.exterior.coords]
output = os.environ.get('BAKED_OUTPUT', 'src/simulation/generated-parsons-ends.js')
with open(output, 'w') as handle:
    handle.write('// Generated by scripts/generate-parsons-ends.py; movement 394 right-end relief in model units.\n')
    handle.write('export default ' + json.dumps({'inputDigest': source['digest'], 'clearance': CLEARANCE,
        'samples': SAMPLES, 'rightEndRelief': ring}, separators=(',', ':')) + ';\n')
print(output, len(ring), 'points')
