import json,os
from shapely.geometry import Polygon
from shapely.ops import unary_union
from shapely.affinity import affine_transform
row=json.load(open('/dev/shm/variable-idler-contact.json'))['rows'][0]
blank=Polygon(row['blank']);original=blank.area
cutter=unary_union([Polygon(t) for t in row['parts'][1]['triangles']]).buffer(.001,resolution=2)
for pose in row['generationPoses']:blank=blank.difference(affine_transform(cutter,pose))
blank=blank.simplify(.00005,preserve_topology=True)
assert blank.geom_type=='Polygon' and not blank.interiors
outline=[[round(x,7),round(y,7)] for x,y in blank.exterior.coords]
with open(os.environ.get('BAKED_OUTPUT','src/simulation/generated-elliptical-idler-profile.js'),'w') as f:f.write('// Generated by scripts/generate-elliptical-idler-profile.py.\nexport default '+json.dumps(outline,separators=(',',':'))+';\n')
print({'points':len(outline),'retainedArea':blank.area/original})
