import json,os
from smooth_profile_ease import ease
from shapely.geometry import Polygon
from shapely.ops import unary_union
from shapely.affinity import affine_transform
row=json.load(open('/dev/shm/variable-idler-contact.json'))['rows'][2]
polygons=[unary_union([Polygon(t) for t in p['triangles']]) for p in row.get('generationParts',row['parts'])]
def inverse(p):
 a,b,d,e,x,y=p;det=a*e-b*d
 return[e/det,-b/det,-d/det,a/det,(b*y-e*x)/det,(d*x-a*y)/det]
results=[]
for pair,(a,b) in enumerate(row['pairs']):
 blank=polygons[b];area=blank.area;cutter=polygons[a].buffer(.0008,resolution=2)
 for poses in row['generationPoses']:blank=blank.difference(affine_transform(cutter,inverse(poses[pair])))
 blank=blank.simplify(.00002,preserve_topology=True)
 if blank.geom_type=='MultiPolygon':
  print('pieces',pair,len(blank.geoms),sorted([p.area for p in blank.geoms],reverse=True)[:5],flush=True)
  blank=max(blank.geoms,key=lambda p:p.area)
 assert blank.geom_type=='Polygon';blank=ease(blank);print(pair,blank.area/area,len(blank.exterior.coords),flush=True)
 results.append([[round(x,7),round(y,7)] for x,y in blank.exterior.coords])
with open(os.environ.get('BAKED_OUTPUT','src/simulation/generated-stepped-sector-relief.js'),'w') as f:f.write('// Generated by scripts/generate-stepped-sector-relief.py.\nexport default '+json.dumps(results,separators=(',',':'))+';\n')
