"""Bake 289's pallet backing; requires Shapely 2.0.3 and paired JS exporter."""
import json, sys, math
from pathlib import Path
from shapely.geometry import Polygon, Point, LineString
from shapely import affinity, union_all
raw=json.loads(Path(sys.argv[1] if len(sys.argv)>1 else '/dev/shm/deadbeat-contact-input.json').read_text())
wheel=Polygon(raw['wheel']);sweeps=[]
dx=raw['wheelCenter'][0]-raw['anchorPivot'][0];dy=raw['wheelCenter'][1]-raw['anchorPivot'][1]
for pose in raw['states']:
    moving=affinity.rotate(wheel,pose['wheel'],origin=(0,0),use_radians=True)
    moving=affinity.translate(moving,dx,dy)
    sweeps.append(affinity.rotate(moving,-pose['anchor'],origin=(0,0),use_radians=True))
# Include the continuous analytical working curves before the clearance offset.
# This prevents sampled tooth-tip disks from leaving scalloped load faces.
cutter=union_all([*sweeps,*[LineString(p) for p in raw['paths'].values()]]).buffer(.0005,quad_segs=8)
output={};metrics={}
for name in ['left','right']:
    path=raw['paths'][name];sign=1 if name=='left' else -1
    back=[[x+sign*.27*x/math.hypot(x,y),y+sign*.27*y/math.hypot(x,y)] for x,y in path]
    blank=Polygon(path+back[::-1]).buffer(0)
    cut=blank.difference(cutter).simplify(.00001,preserve_topology=True)
    assert cut.is_valid and cut.geom_type=='Polygon'
    gap=max(Point(p).distance(cut) for p in path)
    assert gap<.001, (name,'working face erased',gap)
    output[name]=[[list(cut.exterior.coords),*[list(h.coords) for h in cut.interiors]]]
    metrics[name]={'blankArea':blank.area,'finalArea':cut.area,'maximumWorkingFaceGap':gap,'vertices':len(cut.exterior.coords)}
output['qualification']={'poses':len(sweeps),'clearance':.0005,'metrics':metrics}
p=Path(__file__).resolve().parents[1]/'src/simulation/generated/deadbeat-contact-profiles.js'
p.write_text('// Generated by scripts/generate-deadbeat-contact.py.\nexport default '+json.dumps(output,separators=(',',':'))+';\n')
print(json.dumps(output['qualification'],indent=2));print('bytes',p.stat().st_size)
