"""Bake bored annular gyro frames; requires manifold3d==3.5.3."""
import json
from pathlib import Path
import manifold3d as m

def ring(radius, width, depth, normal, bore_axis, bore):
    solid = m.Manifold.cylinder(depth, radius+width/2, radius+width/2, 160, True) - m.Manifold.cylinder(depth+.1, radius-width/2, radius-width/2, 160, True)
    if normal == 'y': solid = solid.rotate((90, 0, 0))
    cut = m.Manifold.cylinder(6, bore, bore, 64, True)
    if bore_axis == 'x': cut = cut.rotate((0,90,0))
    if bore_axis == 'y': cut = cut.rotate((90,0,0))
    solid = solid-cut
    assert solid.status() == m.Error.NoError
    mesh=solid.to_mesh()
    return {'positions':[round(float(v),7) for v in mesh.vert_properties[:,:3].reshape(-1)],'indices':mesh.tri_verts.reshape(-1).tolist()}
data={
 'support355':ring(1.77255,.10,.12,'y','x',.096),
 'outer356':ring(2.1735,.15,.12,'z','y',.081),
 'middle356':ring(1.99125,.12,.11,'z','x',.074),
 'inner356':ring(1.674,.11,.10,'y','z',.070),
}
p=Path(__file__).resolve().parents[1]/'src/simulation/generated/gyroscope-rings.js'
p.write_text('// Generated by scripts/generate-gyroscope-rings.py.\nexport default '+json.dumps(data,separators=(',',':'))+';\n')
print({k:len(v['indices'])//3 for k,v in data.items()},p.stat().st_size)
