"""Cut the right Holly rotor with the complete relative sweep of its left mate."""
import json
import math
import os
from shapely.affinity import affine_transform
from shapely.geometry import Polygon

source = json.load(open('/dev/shm/holly-contact.json'))
left = Polygon(source['left'])
original = Polygon(source['right'])
right = original
clearance = 0.0005
samples = 4096
cutter = left.buffer(clearance, resolution=4)
for i in range(samples):
    angle = math.tau * i / samples
    cosine, sine = math.cos(2*angle), math.sin(2*angle)
    relative = affine_transform(cutter, [cosine, -sine, sine, cosine,
        -source['centerDistance']*math.cos(angle), -source['centerDistance']*math.sin(angle)])
    right = right.difference(relative)
assert right.geom_type == 'Polygon' and not right.interiors
right = right.simplify(0.00001, preserve_topology=True)
metadata = {'samples': samples, 'clearance': clearance, 'simplification': 0.00001,
    'retainedAreaFraction': right.intersection(original).area/original.area,
    'addedAreaFraction': right.difference(original).area/original.area,
    'maximumBoundaryChange': right.boundary.hausdorff_distance(original.boundary)}
assert metadata['retainedAreaFraction'] > 0.99
assert metadata['maximumBoundaryChange'] < 0.0145
result = {'outline': [[round(x,7),round(y,7)] for x,y in right.exterior.coords], **metadata}
with open(os.environ.get('BAKED_OUTPUT','src/simulation/generated-holly-mate.js'),'w') as output:
    output.write('// Generated by scripts/generate-holly-mate.py; coordinates are model units.\nexport default ')
    json.dump(result, output, separators=(',',':'))
    output.write(';\n')
print(metadata, 'vertices', len(result['outline']))
