"""Offline sevenfold finite flank cut. Python3, Shapely2 and Node18/npm deps.
Run this script with --check for byte-identical regeneration; artifacts use RAM.
"""
import json,sys,subprocess,tempfile,math
from pathlib import Path
from shapely.geometry import Polygon,Point,LineString
from shapely.prepared import prep
from shapely.ops import unary_union
repo=Path(__file__).resolve().parents[1]
with tempfile.TemporaryDirectory(prefix='seven-tooth-238-',dir='/dev/shm') as work:
    source=Path(work)/'input.json'
    subprocess.run(['node',str(repo/'scripts/export-seven-tooth-238-profiles.mjs'),str(source)],check=True,cwd=repo)
    data=json.loads(source.read_text())
base=Polygon(data['outline'])
cutter=unary_union([Polygon(p).buffer(.0001,quad_segs=4)for p in data['cutters']])
result=base.difference(cutter).simplify(.00001,preserve_topology=True)
assert result.is_valid and result.geom_type=='Polygon' and not result.interiors
# Conservative farthest-visible chords remove the cutter's macro notches.
# Preserve exact tips. Every chord lies within the cleared solid; sevenfold
# replication avoids tiny cutter-order asymmetries and browser contour work.
raw=result
points=list(raw.exterior.coords)[:-1]
radius=math.hypot(*data['outline'][0])
tips=[i for i,p in enumerate(points)if math.hypot(*p)>radius-1e-8]
assert len(tips)==7
chain=points[tips[0]:tips[1]+1]
inside=prep(raw.buffer(1e-10));first=[chain[0]];i=0
while i<len(chain)-1:
    j=len(chain)-1
    while j>i+1 and not inside.covers(LineString([chain[i],chain[j]])):j-=1
    first.append(chain[j]);i=j
first.pop();outline=[]
for k in range(7):
    a=-k*2*math.pi/7;c=math.cos(a);s=math.sin(a)
    outline.extend([[x*c-y*s,x*s+y*c]for x,y in first])
result=Polygon(outline)
assert result.is_valid and not result.interiors
assert result.difference(raw).area<1e-12

qualification={'poses':data['poses']+1,'symmetry':7,'cutterAllowance':.0001,'palletGap':.0005,'palletThickness':.06,
 'amplitude':data['amplitude'],'impulse':data['impulse'],'areaLossFraction':1-result.area/base.area,
 'maximumTipLoss':max(Point(p).distance(result)for p in data['outline'][::2]),
 'boundaryHausdorffDistance':base.boundary.hausdorff_distance(result.boundary),'vertices':len(result.exterior.coords)-1,'smoothing':'contained farthest-visible chords','smoothingOutsideArea':result.difference(raw).area}
assert qualification['areaLossFraction']<.15 and qualification['maximumTipLoss']<.00001,qualification
output={'outline':list(result.exterior.coords)[:-1],'qualification':qualification}
text='// Generated by scripts/generate-seven-tooth-238-profiles.py.\nexport default '+json.dumps(output,separators=(',',':'))+';\n'
file=repo/'src/simulation/baked/seven-tooth-238-profiles.js'
if '--check' in sys.argv:assert file.read_text()==text
else:file.write_text(text)
print(json.dumps(qualification,indent=2));print('bytes',len(text))
