"""Offline finite front tooth relief for 402; Python3, numpy and Shapely2 required.
Run from the repository: python3 scripts/generate-guernsey-contact.py
Preserves the prescribed timing; reports incomplete near-contact lock transfer.
"""
from pathlib import Path
import subprocess
repo=Path(__file__).resolve().parents[1]
subprocess.run(['node',str(repo/'scripts/export-guernsey-contact.mjs')],check=True,cwd=repo)
import json,math,numpy as np
from shapely.geometry import Polygon,LineString,Point
from shapely.affinity import rotate,translate
from shapely.ops import nearest_points,unary_union
x=json.load(open('/dev/shm/guernsey-input.json'));g=x['g'];D=np.array([g['escapeWheelCenter']['x'],g['escapeWheelCenter']['y']]);pitch=g['escapeToothPitch']
head=Polygon([[g['escapeWheelRootRadius']-.045,-.07],[g['escapeWheelTipRadius'],0],[g['escapeWheelRootRadius']+.055,.095]])
profiles={}
for key,pts in x['profiles'].items():
 p=np.array(pts);t=p[1]-p[0];n=np.array([-t[1],t[0]])/np.linalg.norm(t)
 q=min(x['poses'],key=lambda q:abs(q['time']-(0 if key=='upper'else 2)));a=q['lever'];N=np.array([[math.cos(a),-math.sin(a)],[math.sin(a),math.cos(a)]])@n
 wp=np.array([[math.cos(a),-math.sin(a)],[math.sin(a),math.cos(a)]])@p[0]
 sign=1 if np.cross(wp-D,N)>0 else -1
 # pallet material lies opposite the wheel's useful reaction normal
 curve=LineString(p); shape=curve.buffer(-sign*.075,single_sided=True,join_style=2)
 profiles[key]=shape
 print(key,'sign',sign,'area',shape.area)
scale=g['escapeWheelTipRadius']/.91
rear_foot=[[a*scale,b*scale]for a,b in[[.65,.20],[.91,0],[.905,.12]]]
head=Polygon(rear_foot)
cutters=[]
for q in x['poses']:
 for p in profiles.values():
  w=translate(rotate(p,q['lever'],origin=(0,0),use_radians=True),*-D)
  for j in range(15):
   c=rotate(w,-q['wheel']-j*pitch,origin=(0,0),use_radians=True)
   if c.distance(head)<.001:cutters.append(c)
head=head.difference(unary_union(cutters).buffer(.0005,quad_segs=3))
print('HEAD',head.geom_type,head.area)
# Disjoint front lands share the continuous rear foot; retain each working land.
heads=list(head.geoms) if head.geom_type=='MultiPolygon' else [head]
print("connected head area",head.area)
assert head.is_valid and head.area>.001
reports={key:{'maxGap':0,'wheelMin':1,'impulseMin':1,'closeSamples':0,'impulseSamples':0}for key in profiles};worst=0
for q in x['poses'][::4]:
 for key,p in profiles.items():
  world=rotate(p,q['lever'],origin=(0,0),use_radians=True)
  for j in range(15):
   h=translate(rotate(head,q['wheel']+j*pitch,origin=(0,0),use_radians=True),*D)
   worst=max(worst,h.intersection(world).area)
  con=q['contact']
  if not con or con['side']!=key:continue
  h=translate(rotate(head,q['wheel']+con['toothIndex']*pitch,origin=(0,0),use_radians=True),*D)
  a,b=nearest_points(h,world);gap=a.distance(b);
  if gap>reports[key]['maxGap']:reports[key]['maxGap']=gap;reports[key]['gapWitnessTime']=q['time']
  if gap>1e-8 and gap<.005:
   reports[key]['closeSamples']+=1
   a=np.array(a.coords[0]);b=np.array(b.coords[0]);n=(a-b)/gap;wm=float(np.cross(a-D,n));lm=float(np.cross(b,-n));reports[key]['wheelMin']=min(reports[key]['wheelMin'],wm)
   if con['mode']=='impulse':reports[key]['impulseSamples']+=1;reports[key]['impulseMin']=min(reports[key]['impulseMin'],lm*(-1 if key=='upper'else 1))
print('result',worst,reports)
assert worst<1e-10
for report in reports.values():
 assert report['wheelMin']>0 and report['impulseMin']>0 and report['impulseSamples']>=5
result={'heads':[list(p.exterior.coords)for p in heads],'rearFoot':rear_foot,'profiles':{k:list(p.exterior.coords)for k,p in profiles.items()},'report':{'poses':257,'maxOverlapArea':worst,'branches':reports,'runningAllowance':.0005,'completeLoadedHandoff':False}}
import sys
out=repo/'src/simulation/baked/guernsey-contact.js'
text='// Generated by scripts/generate-guernsey-contact.py; do not hand edit.\nexport const guernseyContact = '+json.dumps(result,separators=(',',':'))+';\n'
if '--check' in sys.argv:
 assert out.read_text()==text,'Baked geometry differs; regenerate and review.'
 print('Byte-identical baked geometry')
else:out.write_text(text)
