"""Bake the fixed receiver's round discharge opening; manifold3d==3.5.3."""
import json
from pathlib import Path
import manifold3d as m

outer = m.Manifold.cylinder(2.18, 1.34, 1.34, 96, True).rotate((90, 0, 0))
inner = m.Manifold.cylinder(2.3, 1.285, 1.285, 96, True).rotate((90, 0, 0))
port = m.Manifold.cylinder(1.0, .285, .285, 64, True).rotate((0, 90, 0)).translate((1.3, -.71, 0))
wall = outer - inner - port
assert wall.status() == m.Error.NoError
mesh = wall.to_mesh()
data = {'positions': [round(float(v), 7) for v in mesh.vert_properties[:, :3].reshape(-1)], 'indices': mesh.tri_verts.reshape(-1).tolist()}
p = Path(__file__).resolve().parents[1] / 'src/simulation/generated/oscillating-column-port.js'
p.write_text('// Generated by scripts/generate-oscillating-column-port.py.\nexport default ' + json.dumps(data, separators=(',', ':')) + ';\n')
print(wall.num_tri(), p.stat().st_size)
