"""Finite pallet/anchor envelope; Python with shapely==2.0.3, input from paired exporter."""
import json, sys, math
from pathlib import Path
from shapely.geometry import Polygon
from shapely import affinity, union_all
from shapely.ops import nearest_points
raw=json.loads(Path(sys.argv[1] if len(sys.argv)>1 else '/dev/shm/anchor-envelope-input.json').read_text())
result={}
for model in raw:
    profiles=model['profiles'];wheel=Polygon(profiles['wheel']);sweeps=[]
    dx=model['wheelCenter'][0]-model['anchorPivot'][0];dy=model['wheelCenter'][1]-model['anchorPivot'][1]
    for pose in model['states']:
        moving=affinity.rotate(wheel,pose['wheel'],origin=(0,0),use_radians=True)
        moving=affinity.translate(moving,dx,dy)
        sweeps.append(affinity.rotate(moving,-pose['anchor'],origin=(0,0),use_radians=True))
    cutter=union_all(sweeps).buffer(.0015,quad_segs=8)
    assert cutter.is_valid and not cutter.is_empty
    output={}
    for name in ['anchor','left','right']:
        if name=='anchor': blank=Polygon(profiles[name]).buffer(0)
        else:
            path=model['paths'][name]; sign=1 if name=='left' else -1
            back=[[x+sign*.30*x/math.hypot(x,y),y+sign*.30*y/math.hypot(x,y)] for x,y in path]
            blank=Polygon(path+back[::-1]).buffer(0)
        cut=blank.difference(cutter).simplify(.00005,preserve_topology=True)
        assert cut.is_valid and not cut.is_empty
        pieces=[cut] if cut.geom_type=='Polygon' else list(cut.geoms)
        output[name]=[[list(p.exterior.coords),*[list(h.coords) for h in p.interiors]] for p in pieces if p.area>1e-7]
        print(model['id'],name,'area',blank.area,'->',cut.area,'parts',len(output[name]),'vertices',sum(len(r) for p in output[name] for r in p))
    a=union_all([Polygon(p[0],p[1:]) for p in output['anchor']]);b=union_all([Polygon(p[0],p[1:]) for p in output['left']]);pa,pb=nearest_points(a,b)
    output['leftAttachment']=[list(pa.coords)[0],list(b.centroid.coords)[0]]
    result[str(model['id'])]=output
p=Path(__file__).resolve().parents[1]/'src/simulation/generated/anchor-escapement-envelopes.js'
p.write_text('// Generated by scripts/generate-anchor-escapement-envelope.py.\nexport default '+json.dumps(result,separators=(',',':'))+';\n')
print('bytes',p.stat().st_size)
