"""Offline finite 485 head cover; requires manifold3d==3.5.3 (and its numpy dependency)."""
import json
from pathlib import Path
import manifold3d as m

# Upper spherical cover with an actual axial shaft passage. Local cap origin
# is its equator; the horizontal shaft lies .24 above it.
cover = (m.Manifold.sphere(.8, 72) - m.Manifold.sphere(.755, 72)) ^ m.Manifold.cube((2, 1, 2)).translate((-1, 0, -1))
passage = m.Manifold.cylinder(1, .122, .122, 64, True).translate((0, .24, .5))
cover = cover - passage
assert cover.status() == m.Error.NoError
mesh = cover.to_mesh()
data = {'positions': [round(float(v), 7) for v in mesh.vert_properties[:, :3].reshape(-1)], 'indices': mesh.tri_verts.reshape(-1).tolist()}
path = Path(__file__).resolve().parents[1] / 'src/simulation/generated/windmill-cap.js'
path.write_text('// Generated by scripts/generate-windmill-cap.py; do not hand edit.\nexport default ' + json.dumps(data, separators=(',', ':')) + ';\n')
print(f'{cover.num_tri()} triangles, {path.stat().st_size} bytes')
