"""Bake bored annular gyro frames; requires manifold3d==3.5.3."""
import json
from pathlib import Path
import manifold3d as m

def axis_cylinder(length, radius, axis, segments):
    c = m.Manifold.cylinder(length, radius, radius, segments, True)
    if axis == 'x': c = c.rotate((0,90,0))
    if axis == 'y': c = c.rotate((90,0,0))
    return c

def ring(radius, width, depth, normal, bore_axis, bore, bosses=()):
    # Plain annulus about its normal, with optional round bosses: each boss is
    # a cylinder of radius r about a pivot axis through the ring's crossing,
    # clipped to the ring's own inner and outer radii, so a pin stands centred
    # in a round pad rather than on a band narrower than the pin.
    outer_r, inner_r = radius+width/2, radius-width/2
    solid = m.Manifold.cylinder(depth, outer_r, outer_r, 160, True) - m.Manifold.cylinder(depth+.1, inner_r, inner_r, 160, True)
    if bosses:
        span = 2*max(r for _, r in bosses)+.1
        annulus = m.Manifold.cylinder(span, outer_r, outer_r, 160, True) - m.Manifold.cylinder(span+.1, inner_r, inner_r, 160, True)
        for axis, r in bosses:
            solid = solid + (annulus ^ axis_cylinder(6, r, axis, 64))
    if normal == 'y': solid = solid.rotate((90, 0, 0))
    solid = solid-axis_cylinder(6, bore, bore_axis, 64)
    assert solid.status() == m.Error.NoError
    mesh=solid.to_mesh()
    return {'positions':[round(float(v),7) for v in mesh.vert_properties[:,:3].reshape(-1)],'indices':mesh.tri_verts.reshape(-1).tolist()}

data={
 # Ring A is Brown's broad flat band: the inner edge keeps its clearance to
 # disk C's rim (1.72255), the band runs out to 1.93 and is 0.07 deep.
 'support355':ring(1.82630,.2075,.07,'y','x',.096),
 'outer356':ring(2.1735,.15,.12,'z','y',.081,(('y',.13),)),
 'middle356':ring(1.99125,.12,.11,'z','x',.074,(('x',.12),('y',.12))),
 'inner356':ring(1.674,.11,.10,'y','z',.070,(('x',.11),('y',.11))),
}
p=Path(__file__).resolve().parents[1]/'src/simulation/generated/gyroscope-rings.js'
p.write_text('// Generated by scripts/generate-gyroscope-rings.py.\nexport default '+json.dumps(data,separators=(',',':'))+';\n')
print({k:len(v['indices'])//3 for k,v in data.items()},p.stat().st_size)
