import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');
export function makeElbowPawlPhysics(mujoco,visual,{timestep=.0005,period=4.4,stroke=.78,outputFriction=3,bearingTime=.001,bearingImpedance=.999,outputDamping=.005,pawlDamping=.02,pawlSpring=0,pawlRest=-.1,friction=0,gravity=-9.81,contactTime=.001,pawlInitial=0}={}){
 if(![timestep,period,stroke,contactTime,bearingTime].every(v=>Number.isFinite(v)&&v>0)||![outputFriction,outputDamping,pawlDamping,pawlSpring,friction].every(v=>Number.isFinite(v)&&v>=0)||![gravity,pawlRest,pawlInitial].every(Number.isFinite)||!(bearingImpedance>0&&bearingImpedance<1))throw new RangeError('Invalid 155 physics options');
 const u=visual.root.userData,f=u.profile,names=['carrier','rod','pawl','output','slider'],mass=Object.fromEntries(names.map(n=>[n,rigidFamilyInertia(u.parts,u.families,n)])),density=1/mass.output.volume,assets=[],groups={};
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const geoms=(name,mask,other)=>u.cells[name].map((cell,i)=>{const id=name+i;groups[id]=name;assets.push(`<mesh name="${id}" vertex="${vec(cell.flat())}"/>`);return `<geom name="${id}" type="mesh" mesh="${id}" contype="${mask}" conaffinity="${other}"/>`;}).join('');
 const cog=geoms('cog',1,2),click=geoms('click',2,1);
 const xml=`<mujoco model="155 reversible click"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 ${gravity} 0" integrator="discrete" solver="Newton" iterations="80" tolerance="1e-10" cone="elliptic"><flag multiccd="disable" diagexact="enable"/></option><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp=".99 .999 .001"/><equality solref=".002 1" solimp=".999 .9999 .0001"/></default><asset>${assets.join('')}</asset><worldbody><body name="carrier"><joint name="carrier" damping=".001"/>${inertia('carrier')}<body name="rod" pos="${vec([...f.crank,0])}"><joint name="rod" damping=".001"/>${inertia('rod')}<site name="rodEnd" pos="${vec([...f.rodVector,.60])}"/></body><body name="pawl" pos="${vec([...f.pawlPivot,0])}"><joint name="pawl" damping="${pawlDamping}" stiffness="${pawlSpring}"/>${inertia('pawl')}${click}</body></body><body name="output"><joint name="output" damping="${outputDamping}" frictionloss="${outputFriction}" solreffriction="${bearingTime} 1" solimpfriction="${bearingImpedance} ${bearingImpedance} .001"/>${inertia('output')}${cog}</body><body name="slider" pos="${vec([...f.rodEnd,0])}"><joint name="slider" type="slide" axis="0 1 0" damping=".01"/>${inertia('slider')}<site name="sliderPin" pos="0 0 .60"/></body></worldbody><equality><connect site1="rodEnd" site2="sliderPin"/></equality><actuator><position joint="slider" kp="10000" kv="200"/></actuator></mujoco>`;
 const omega=2*Math.PI/period,input=time=>({position:-stroke*(1-Math.cos(omega*time))/2,velocity:-stroke*omega*Math.sin(omega*time)/2});
 const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{const j=id('mjOBJ_JOINT','pawl'),q=model.jnt_qposadr[j],base=0;data.qpos[q]=base+pawlInitial;model.qpos_spring[q]=base+pawlRest;},beforeStep:({data,time})=>{const s=input(time);data.ctrl[0]=s.position+.02*s.velocity;}});
 const joints=Object.fromEntries(names.map(n=>{const id=p.id('mjOBJ_JOINT',n);return[n,{q:p.model.jnt_qposadr[id],v:p.model.jnt_dofadr[id]}];}));
 return Object.assign(p,{joints,bodies:Object.fromEntries(names.map(n=>[n,p.id('mjOBJ_BODY',n)])),geomGroups:Object.fromEntries(Object.entries(groups).map(([id,name])=>[p.id('mjOBJ_GEOM',id),name])),description:{xml,mass,density,input,options:{timestep,period,stroke,outputFriction,bearingTime,bearingImpedance,outputDamping,pawlDamping,pawlSpring,pawlRest,friction,gravity,contactTime,side:f.side,pawlInitial},assumptions:'Candidate only; full rendered assembly is not yet qualified. Pawl side is a separate physical installation, turned over about the radial axis; no in-plane reversal is simulated. Only an ideal vertical input slide is actuated. An ideal top pin closes the rod linkage. Gravity seats the freely hinged click with inferred hinge damping. Output bearing friction represents an inferred resisting tool load. No output angle or click angle is prescribed.'}});
}
