import {makeWaveCamContactSolver} from './quasistatic.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
import {waveCamContactMeshes} from './contact-mesh.js';
export function makeWaveCamPhysics(mujoco,{timestep=.0005,segments=360,clearance=.001,profileTolerance=null,profileType='radial',camSpeed=Math.PI/9,outputMass=1,contact=true,collision='mpr',ccdTolerance=1e-10,ccdIterations=200,driveStiffness=100000,driveDamping=1000}={}){
 if(!['native-single','native-multi','mpr'].includes(collision))throw new RangeError('Unknown wave cam collision mode');
 const flags=collision==='native-single'?'<flag multiccd="disable"/>':collision==='mpr'?'<flag nativeccd="disable"/>':'';
 const {geometry:g,meshes}=waveCamContactMeshes({segments,clearance,profileTolerance,profileType}),dx=g.rollerX-g.pivot[0],dy=g.rollerY-g.pivot[1],arm=Math.hypot(dx,dy),theta=Math.atan2(dy,dx),leftLength=Math.hypot(g.outputPin[0]-g.pivot[0],g.outputPin[1]-g.pivot[1]),left=[g.pivot[0]-leftLength*Math.cos(theta),g.pivot[1]-leftLength*Math.sin(theta),g.pivot[2]];
 const assets=meshes.map(m=>`<mesh name="${m.name}" vertex="${m.vertices.flat().join(' ')}"/>`).join(''),geoms=meshes.map(m=>`<geom type="mesh" mesh="${m.name}" mass="0" contype="${contact?1:0}" conaffinity="${contact?2:0}"/>`).join('');
 const xml=`<mujoco><compiler angle="radian"/><option timestep="${timestep}" gravity="0 -98.1 0" integrator="implicitfast" solver="Newton" iterations="80" tolerance="1e-10" ccd_tolerance="${ccdTolerance}" ccd_iterations="${ccdIterations}">${flags}</option><default><geom contype="0" conaffinity="0" friction=".4 .001 .0001" solref=".003 1" solimp=".999 .999 .001"/><equality solref=".002 1" solimp=".9999 .9999 .001"/><site size=".01"/></default><asset>${assets}</asset><worldbody><body name="cam"><joint name="cam" axis="0 1 0"/><inertial pos="0 3 0" mass="1" diaginertia=".4 .5 .4"/>${geoms}</body><body name="rocker" pos="${g.pivot.join(' ')}" euler="0 0 ${theta}"><joint name="rocker" axis="0 0 1" damping=".02"/><geom type="capsule" fromto="-${leftLength} 0 0 ${arm} 0 0" size=".07" mass=".08"/><site name="output-pin" pos="-${leftLength} 0 0"/><body name="roller" pos="${arm} 0 ${g.rollerZ-g.pivot[2]}"><joint name="roller" axis="0 0 1" damping=".0001"/><geom name="roller" type="cylinder" size="${g.rollerRadius} ${g.rollerDepth/2}" mass=".2" contype="2" conaffinity="1"/></body></body><body name="output" pos="${left.join(' ')}"><joint name="output" type="slide" axis="0 1 0" damping=".02"/><inertial pos="0 -1 0" mass="${outputMass}" diaginertia=".05 .001 .05"/><body name="shoe"><joint name="shoe" type="slide" axis="1 0 0"/><inertial pos="0 0 0" mass=".005" diaginertia=".0001 .0001 .0001"/><site name="shoe-pin"/></body></body></worldbody><equality><connect site1="output-pin" site2="shoe-pin"/></equality><actuator><position joint="cam" kp="${driveStiffness}" kv="${driveDamping}"/></actuator></mujoco>`;
 let dofs;const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{dofs=Object.fromEntries(['cam','rocker','roller','output','shoe'].map(n=>[n,model.jnt_dofadr[id('mjOBJ_JOINT',n)]]));if(profileType==='radial'){const seated=makeWaveCamContactSolver({geometry:g}).solve(0);data.qpos[dofs.rocker]=seated.rocker-theta;data.qpos[dofs.output]=seated.outputY-left[1];data.qpos[dofs.shoe]=seated.shoeX;}data.qvel[dofs.cam]=camSpeed;},beforeStep:({data,time})=>{data.ctrl[0]=camSpeed*(time-timestep)+(driveDamping/driveStiffness)*camSpeed;}}),roller=p.id('mjOBJ_GEOM','roller'),sites=['output-pin','shoe-pin'].map(n=>p.id('mjOBJ_SITE',n));
 return Object.assign(p,{geometry:{...g,arm,leftLength,theta,left},description:{movement:165,timestep,segments,clearance,profileTolerance,profileType,camSpeed,outputMass,contact,collision,ccdTolerance,ccdIterations,driveStiffness,driveDamping,assumptions:'Evenly spaced sinusoidal wave profile, inferred narrow roller and outer-lip contact. Passive rocker/roller and gravity-loaded output bar; ideal horizontal crosshead freedom at the output pin. One cam actuator. Unregistered native study.'},state:()=>{
  mujoco.mj_kinematics(p.model,p.data);let penetration=0;for(let i=0;i<p.data.ncon;i++)penetration=Math.max(penetration,-p.data.contact.get(i).dist);
  return{time:p.data.time,cam:p.data.qpos[dofs.cam],rocker:theta+p.data.qpos[dofs.rocker],rollerAngle:p.data.qpos[dofs.roller],rollerSpeed:p.data.qvel[dofs.roller],rollerCenter:Array.from(p.data.geom_xpos.slice(3*roller,3*roller+3)),outputY:left[1]+p.data.qpos[dofs.output],shoeX:p.data.qpos[dofs.shoe],contacts:p.data.ncon,penetration,closure:Math.hypot(...[0,1,2].map(i=>p.data.site_xpos[3*sites[0]+i]-p.data.site_xpos[3*sites[1]+i])),qpos:Array.from(p.data.qpos),qvel:Array.from(p.data.qvel)};
 }});
}
