import {rigidFamilyInertia} from '../mujoco/mass.js';
import {createMujocoSimulation} from '../mujoco/simulation.js';
const vec=a=>a.map(v=>Number(v.toPrecision(12))).join(' ');
export function makeDoubleRackPhysics(mujoco,visual,{timestep=.0005,period=8,contactTime=.002,friction=0,load=0,driveGain=2000,guideDamping=.02}={}){
 if(![timestep,period,contactTime,driveGain].every(x=>Number.isFinite(x)&&x>0)||![friction,guideDamping].every(x=>Number.isFinite(x)&&x>=0)||!Number.isFinite(load))throw new RangeError('Invalid double-rack physics options');
 const u=visual.root.userData,mass=Object.fromEntries(['pinion','frame'].map(n=>[n,rigidFamilyInertia(u.workingParts??u.parts,u.families,n)])),density=1/mass.frame.volume,assets=[];
 const inertia=n=>{const m=mass[n];return `<inertial pos="${vec(m.centroid)}" mass="${m.volume*density}" fullinertia="${vec(m.inertia.map(v=>v*density))}"/>`;};
 const geoms=(n,mask,other)=>u.cells[n].map((cell,i)=>{const id=n+i;assets.push(`<mesh name="${id}" vertex="${vec(cell.flat())}"/>`);return `<geom name="${id}" type="mesh" mesh="${id}" contype="${mask}" conaffinity="${other}"/>`;}).join('');
 const pinion=geoms('pinion',1,2),frame=geoms('frame',2,1),omega=2*Math.PI/period;
 const xml=`<mujoco model="114 alternating double rack"><compiler angle="radian" inertiafromgeom="false"/><option timestep="${timestep}" gravity="0 -9.81 0" integrator="implicitfast" solver="Newton" cone="elliptic" iterations="60" tolerance="1e-10"/><default><geom condim="${friction?3:1}" friction="${friction} .001 .001" solref="${contactTime} 1" solimp=".9999 .99999 .0001"/></default><asset>${assets.join('')}</asset><worldbody><body name="pinion"><joint name="pinion" axis="0 0 1" damping=".001"/>${inertia('pinion')}${pinion}</body><body name="frame"><joint name="frame" type="slide" axis="1 0 0" damping="${guideDamping}"/>${inertia('frame')}${frame}</body></worldbody><actuator><position joint="pinion" kp="${driveGain}" kv="40"/></actuator></mujoco>`;
 const physics=createMujocoSimulation(mujoco,{xml,initialize:({data})=>{data.qvel[0]=omega;data.qfrc_applied[1]=load;},beforeStep:({data,time})=>{data.ctrl[0]=omega*time+40/driveGain*omega;}});
 return Object.assign(physics,{bodies:Object.fromEntries(['pinion','frame'].map(n=>[n,physics.id('mjOBJ_BODY',n)])),description:{xml,mass,density,input:t=>({angle:omega*t,velocity:omega}),options:{timestep,period,contactTime,friction,load,driveGain,guideDamping},assumptions:'Only the pinion is actuated at uniform speed. Native tooth and enclosure contact move the passive frame slide. The shaft axis and horizontal guide are ideal. The half-sector end teeth are cut with a mating-rack envelope; this construction path never sets the native rack position. Tooth form, phase, depth, loads and timing are reconstructed.'}});
}
