import {createMujocoSimulation} from '../mujoco/simulation.js';

// Native linkage study; source-shaped solids and bevel transmission are not
// replaced yet. Only spindle rotation is actuated; sleeve and arms are passive.
export function makeBallGovernorPhysics(mujoco,{timestep=.0005,period=8,variableSpeed=true,spindleDrive=true}={}){
 const g={topY:2.8,pivotRadius:.405,ballArm:3.858,elbowArm:2.388,lowerLink:2.351,sleeveRadius:.333,ballRadius:.612,initialSpread:.365,highSpread:.60,gravity:98.1};
 const theta=g.initialSpread,elbowR=g.pivotRadius+g.elbowArm*Math.sin(theta),drop=Math.sqrt(g.lowerLink**2-(elbowR-g.sleeveRadius)**2),sleeveY=-g.elbowArm*Math.cos(theta)-drop,lowerAngle=Math.asin((g.sleeveRadius-elbowR)/g.lowerLink);
 const equilibriumSpeed=a=>Math.sqrt(g.gravity*Math.tan(a)/(g.pivotRadius+g.ballArm*Math.sin(a))),low=equilibriumSpeed(theta),high=equilibriumSpeed(g.highSpread),mean=(low+high)/2,half=(high-low)/2,k=2*Math.PI/period;
 const drive=time=>variableSpeed?{angle:mean*time-half*Math.sin(k*time)/k,speed:mean-half*Math.cos(k*time)}:{angle:low*time,speed:low};
 let arms='',connections='';
 for(const sign of [-1,1]){
  const name=sign<0?'left':'right';
  arms+=`<body name="${name}" pos="${sign*g.pivotRadius} 0 0" euler="0 0 ${sign*theta}"><joint name="${name}-spread" axis="0 0 ${sign}" damping=".08"/><geom type="capsule" fromto="0 0 0 0 -${g.ballArm} 0" size=".035" mass=".02"/><geom name="${name}-ball" type="sphere" pos="0 -${g.ballArm} 0" size="${g.ballRadius}" mass="1"/><site name="${name}-ball-center" pos="0 -${g.ballArm} 0"/><body name="${name}-link" pos="0 -${g.elbowArm} 0" euler="0 0 ${sign*(lowerAngle-theta)}"><joint name="${name}-link" axis="0 0 ${sign}" damping=".02"/><geom type="capsule" fromto="0 0 0 0 -${g.lowerLink} 0" size=".03" mass=".02"/><site name="${name}-end" pos="0 -${g.lowerLink} 0"/></body></body>`;
  connections+=`<connect site1="${name}-end" site2="${name}-sleeve" solref=".002 1" solimp=".9999 .9999 .001"/>`;
 }
 const xml=`<mujoco><compiler angle="radian"/><option timestep="${timestep}" gravity="0 -${g.gravity} 0" integrator="implicitfast" solver="Newton" iterations="80" tolerance="1e-10"/><default><geom contype="0" conaffinity="0"/><site size=".01"/></default><worldbody><body name="rotor" pos="0 ${g.topY} 0"><joint name="spindle" axis="0 1 0"/><inertial pos="0 0 0" mass=".2" diaginertia=".05 .05 .05"/>${arms}<body name="sleeve" pos="0 ${sleeveY} 0"><joint name="sleeve" type="slide" axis="0 1 0" damping=".1"/><geom type="box" size=".35 .12 .12" mass=".1"/><site name="left-sleeve" pos="-${g.sleeveRadius} 0 0"/><site name="right-sleeve" pos="${g.sleeveRadius} 0 0"/></body></body></worldbody><equality>${connections}</equality>${spindleDrive?'<actuator><position joint="spindle" kp="10000" kv="100"/></actuator>':''}</mujoco>`;
 let spindle,slide,left,right;const p=createMujocoSimulation(mujoco,{xml,initialize:({model,data,id})=>{spindle=model.jnt_dofadr[id('mjOBJ_JOINT','spindle')];slide=model.jnt_dofadr[id('mjOBJ_JOINT','sleeve')];left=model.jnt_dofadr[id('mjOBJ_JOINT','left-spread')];right=model.jnt_dofadr[id('mjOBJ_JOINT','right-spread')];if(spindleDrive)data.qvel[spindle]=low;},beforeStep:({data,time})=>{if(spindleDrive){const d=drive(time);data.ctrl[0]=d.angle+.01*d.speed;}}});
 const sites=['left-end','left-sleeve','right-end','right-sleeve'].map(n=>p.id('mjOBJ_SITE',n));
 return Object.assign(p,{geometry:g,description:{movement:161,timestep,period,variableSpeed,spindleDrive,lowSpeed:low,highSpeed:high,assumptions:'Diagnostic source-proportioned linkage with ideal hinges/slider, two 1 kg balls, inferred light links and sleeve, gravity at 0.1 m per world unit, and only spindle position actuation. No valve load, feedback engine or bevel contact yet. Speed endpoints are unloaded point-ball equilibria; actual finite-mass dynamics need comparison.'},state:()=>{mujoco.mj_kinematics(p.model,p.data);const pos=id=>Array.from(p.data.site_xpos.slice(3*id,3*id+3));return{time:p.data.time,spindle:p.data.qpos[spindle],speed:p.data.qvel[spindle],targetSpeed:drive(p.data.time).speed,leftSpread:theta+p.data.qpos[left],rightSpread:theta+p.data.qpos[right],sleeveY:g.topY+sleeveY+p.data.qpos[slide],connectionErrors:[0,2].map(i=>Math.hypot(...pos(sites[i]).map((x,k)=>x-pos(sites[i+1])[k]))),qpos:Array.from(p.data.qpos),qvel:Array.from(p.data.qvel)};}});
}
